// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class BlockNoteBlock {
    "id": string;
    "type": string;
    "props"?: { [_: string]: any };
    "content"?: json$0.RawMessage;
    "children"?: BlockNoteBlock[];

    /** Creates a new BlockNoteBlock instance. */
    constructor($$source: Partial<BlockNoteBlock> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockNoteBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): BlockNoteBlock {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField2_0($$parsedSource["props"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new BlockNoteBlock($$parsedSource as Partial<BlockNoteBlock>);
    }
}

export class Document {
    "path": string;
    "project_alias": string;
    "title": string;
    "mtime_ns": number;
    "size_bytes": number;
    "has_code": boolean;
    "has_images": boolean;
    "has_links": boolean;
    "created_at": string;
    "updated_at": string;
    "deleted_at": string;
    "tags": string[];

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("project_alias" in $$source)) {
            this["project_alias"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("mtime_ns" in $$source)) {
            this["mtime_ns"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }
        if (!("has_code" in $$source)) {
            this["has_code"] = false;
        }
        if (!("has_images" in $$source)) {
            this["has_images"] = false;
        }
        if (!("has_links" in $$source)) {
            this["has_links"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new Document($$parsedSource as Partial<Document>);
    }
}

export class DocumentFile {
    "meta": DocumentMeta;
    "blocks": BlockNoteBlock[];

    /** Creates a new DocumentFile instance. */
    constructor($$source: Partial<DocumentFile> = {}) {
        if (!("meta" in $$source)) {
            this["meta"] = (new DocumentMeta());
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentFile {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField1_0($$parsedSource["blocks"]);
        }
        return new DocumentFile($$parsedSource as Partial<DocumentFile>);
    }
}

export class DocumentMeta {
    "project": string;
    "title": string;
    "tags": string[];
    "aliases"?: string[];
    "created": time$0.Time;
    "updated": time$0.Time;

    /** Creates a new DocumentMeta instance. */
    constructor($$source: Partial<DocumentMeta> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentMeta {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        return new DocumentMeta($$parsedSource as Partial<DocumentMeta>);
    }
}

export class DocumentWithTags {
    "path": string;
    "project_alias": string;
    "title": string;
    "mtime_ns": number;
    "size_bytes": number;
    "has_code": boolean;
    "has_images": boolean;
    "has_links": boolean;
    "created_at": string;
    "updated_at": string;
    "deleted_at": string;
    "tags": string[];
    "File": DocumentFile | null;
    "Tags": string[];

    /** Creates a new DocumentWithTags instance. */
    constructor($$source: Partial<DocumentWithTags> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("project_alias" in $$source)) {
            this["project_alias"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("mtime_ns" in $$source)) {
            this["mtime_ns"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }
        if (!("has_code" in $$source)) {
            this["has_code"] = false;
        }
        if (!("has_images" in $$source)) {
            this["has_images"] = false;
        }
        if (!("has_links" in $$source)) {
            this["has_links"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("File" in $$source)) {
            this["File"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentWithTags instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentWithTags {
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        if ("File" in $$parsedSource) {
            $$parsedSource["File"] = $$createField12_0($$parsedSource["File"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField13_0($$parsedSource["Tags"]);
        }
        return new DocumentWithTags($$parsedSource as Partial<DocumentWithTags>);
    }
}

export class SaveRequest {
    "Path": string;
    "ProjectAlias": string;
    "Title": string;
    "Blocks": BlockNoteBlock[];
    "Tags": string[];

    /** Creates a new SaveRequest instance. */
    constructor($$source: Partial<SaveRequest> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("ProjectAlias" in $$source)) {
            this["ProjectAlias"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Blocks" in $$source)) {
            this["Blocks"] = [];
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveRequest {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Blocks" in $$parsedSource) {
            $$parsedSource["Blocks"] = $$createField3_0($$parsedSource["Blocks"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField4_0($$parsedSource["Tags"]);
        }
        return new SaveRequest($$parsedSource as Partial<SaveRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = BlockNoteBlock.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = DocumentMeta.createFrom;
const $$createType5 = DocumentFile.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
