// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class BlockNoteBlock {
    /**
     * Creates a new BlockNoteBlock instance.
     * @param {Partial<BlockNoteBlock>} [$$source = {}] - The source object to create the BlockNoteBlock.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_: string]: any } | undefined}
             */
            this["props"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BlockNoteBlock[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockNoteBlock instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockNoteBlock}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField2_0($$parsedSource["props"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new BlockNoteBlock(/** @type {Partial<BlockNoteBlock>} */($$parsedSource));
    }
}

export class Document {
    /**
     * Creates a new Document instance.
     * @param {Partial<Document>} [$$source = {}] - The source object to create the Document.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("project_alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_alias"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("mtime_ns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtime_ns"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_bytes"] = 0;
        }
        if (!("has_code" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_code"] = false;
        }
        if (!("has_images" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_images"] = false;
        }
        if (!("has_links" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_links"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deleted_at"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Document}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new Document(/** @type {Partial<Document>} */($$parsedSource));
    }
}

export class DocumentFile {
    /**
     * Creates a new DocumentFile instance.
     * @param {Partial<DocumentFile>} [$$source = {}] - The source object to create the DocumentFile.
     */
    constructor($$source = {}) {
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {DocumentMeta}
             */
            this["meta"] = (new DocumentMeta());
        }
        if (!("blocks" in $$source)) {
            /**
             * @member
             * @type {BlockNoteBlock[]}
             */
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentFile}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField1_0($$parsedSource["blocks"]);
        }
        return new DocumentFile(/** @type {Partial<DocumentFile>} */($$parsedSource));
    }
}

export class DocumentMeta {
    /**
     * Creates a new DocumentMeta instance.
     * @param {Partial<DocumentMeta>} [$$source = {}] - The source object to create the DocumentMeta.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["aliases"] = undefined;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentMeta}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        return new DocumentMeta(/** @type {Partial<DocumentMeta>} */($$parsedSource));
    }
}

export class DocumentWithTags {
    /**
     * Creates a new DocumentWithTags instance.
     * @param {Partial<DocumentWithTags>} [$$source = {}] - The source object to create the DocumentWithTags.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("project_alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_alias"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("mtime_ns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtime_ns"] = 0;
        }
        if (!("size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_bytes"] = 0;
        }
        if (!("has_code" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_code"] = false;
        }
        if (!("has_images" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_images"] = false;
        }
        if (!("has_links" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_links"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deleted_at"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {DocumentFile | null}
             */
            this["File"] = null;
        }
        if (!("Tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentWithTags instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentWithTags}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        if ("File" in $$parsedSource) {
            $$parsedSource["File"] = $$createField12_0($$parsedSource["File"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField13_0($$parsedSource["Tags"]);
        }
        return new DocumentWithTags(/** @type {Partial<DocumentWithTags>} */($$parsedSource));
    }
}

/**
 * ExportDocumentRequest contains parameters for exporting a single document
 */
export class ExportDocumentRequest {
    /**
     * Creates a new ExportDocumentRequest instance.
     * @param {Partial<ExportDocumentRequest>} [$$source = {}] - The source object to create the ExportDocumentRequest.
     */
    constructor($$source = {}) {
        if (!("DocumentPath" in $$source)) {
            /**
             * Path to document in vault (e.g., "projects/@myproject/doc-xyz.json")
             * @member
             * @type {string}
             */
            this["DocumentPath"] = "";
        }
        if (!("OutputPath" in $$source)) {
            /**
             * Absolute path where markdown file should be written
             * @member
             * @type {string}
             */
            this["OutputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportDocumentRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportDocumentRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportDocumentRequest(/** @type {Partial<ExportDocumentRequest>} */($$parsedSource));
    }
}

/**
 * ExportProjectRequest contains parameters for exporting an entire project
 */
export class ExportProjectRequest {
    /**
     * Creates a new ExportProjectRequest instance.
     * @param {Partial<ExportProjectRequest>} [$$source = {}] - The source object to create the ExportProjectRequest.
     */
    constructor($$source = {}) {
        if (!("ProjectAlias" in $$source)) {
            /**
             * Project alias (e.g., "@myproject")
             * @member
             * @type {string}
             */
            this["ProjectAlias"] = "";
        }
        if (!("OutputDir" in $$source)) {
            /**
             * Absolute path to directory where markdown files should be written
             * @member
             * @type {string}
             */
            this["OutputDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportProjectRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportProjectRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportProjectRequest(/** @type {Partial<ExportProjectRequest>} */($$parsedSource));
    }
}

export class SaveRequest {
    /**
     * Creates a new SaveRequest instance.
     * @param {Partial<SaveRequest>} [$$source = {}] - The source object to create the SaveRequest.
     */
    constructor($$source = {}) {
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("ProjectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProjectAlias"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Blocks" in $$source)) {
            /**
             * @member
             * @type {BlockNoteBlock[]}
             */
            this["Blocks"] = [];
        }
        if (!("Tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Blocks" in $$parsedSource) {
            $$parsedSource["Blocks"] = $$createField3_0($$parsedSource["Blocks"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField4_0($$parsedSource["Tags"]);
        }
        return new SaveRequest(/** @type {Partial<SaveRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = BlockNoteBlock.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = DocumentMeta.createFrom;
const $$createType5 = DocumentFile.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
