// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(path: string): $CancellablePromise<$models.DocumentWithTags | null> {
    return $Call.ByID(632320575, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HardDelete(path: string): $CancellablePromise<void> {
    return $Call.ByID(2532729615, path);
}

export function HardDeleteBatch(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3013481569, paths);
}

export function HardDeleteByProject(projectAlias: string): $CancellablePromise<void> {
    return $Call.ByID(4159902171, projectAlias);
}

export function ListByProject(projectAlias: string, includeArchived: boolean, limit: number, offset: number): $CancellablePromise<($models.Document | null)[]> {
    return $Call.ByID(1335083133, projectAlias, includeArchived, limit, offset).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Restore(path: string): $CancellablePromise<void> {
    return $Call.ByID(3061308073, path);
}

export function Save(req: $models.SaveRequest): $CancellablePromise<string> {
    return $Call.ByID(549000096, req);
}

export function SoftDelete(path: string): $CancellablePromise<void> {
    return $Call.ByID(298271922, path);
}

export function SoftDeleteByProject(projectAlias: string): $CancellablePromise<void> {
    return $Call.ByID(2680230872, projectAlias);
}

// Private type creation functions
const $$createType0 = $models.DocumentWithTags.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Document.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
