// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportDocument exports a single document to markdown format
 * @param {$models.ExportDocumentRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function ExportDocument(req) {
    return $Call.ByID(2595318286, req);
}

/**
 * ExportProject exports all documents in a project to markdown format
 * @param {$models.ExportProjectRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function ExportProject(req) {
    return $Call.ByID(3183703096, req);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.DocumentWithTags | null>}
 */
export function Get(path) {
    return $Call.ByID(632320575, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function HardDelete(path) {
    return $Call.ByID(2532729615, path);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function HardDeleteBatch(paths) {
    return $Call.ByID(3013481569, paths);
}

/**
 * @param {string} projectAlias
 * @returns {$CancellablePromise<void>}
 */
export function HardDeleteByProject(projectAlias) {
    return $Call.ByID(4159902171, projectAlias);
}

/**
 * @param {string} projectAlias
 * @param {boolean} includeArchived
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<($models.Document | null)[]>}
 */
export function ListByProject(projectAlias, includeArchived, limit, offset) {
    return $Call.ByID(1335083133, projectAlias, includeArchived, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Restore(path) {
    return $Call.ByID(3061308073, path);
}

/**
 * @param {$models.SaveRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function Save(req) {
    return $Call.ByID(549000096, req);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SoftDelete(path) {
    return $Call.ByID(298271922, path);
}

/**
 * @param {string} projectAlias
 * @returns {$CancellablePromise<void>}
 */
export function SoftDeleteByProject(projectAlias) {
    return $Call.ByID(2680230872, projectAlias);
}

// Private type creation functions
const $$createType0 = $models.DocumentWithTags.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Document.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
