// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {system} from '../models';
import {context} from '../models';

export function CheckGitInstalled():Promise<boolean>;

export function GetCurrentDataDirectory():Promise<string>;

export function GetGitStatus():Promise<Record<string, any>>;

export function GetGitSyncConfig():Promise<config.GitSyncConfig>;

export function GetKeepInBackground():Promise<boolean>;

export function GetStartHidden():Promise<boolean>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GitPull():Promise<void>;

export function GitPush():Promise<void>;

export function LogFromFrontend(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function MigrateToGitDirectory(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function Quit():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDBPath(arg1:string):Promise<void>;

export function SetGitSyncConfig(arg1:config.GitSyncConfig):Promise<void>;

export function SetKeepInBackground(arg1:boolean):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetShutdownHandler(arg1:any):Promise<void>;

export function SetStartHidden(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function SyncNow():Promise<void>;

export function ValidateMigrationTarget(arg1:string):Promise<void>;
