// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['system']['Service']['GetSystemInfo']();
}

export function LogFromFrontend(arg1, arg2, arg3) {
  return window['go']['system']['Service']['LogFromFrontend'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['system']['Service']['SetContext'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['system']['Service']['SetDBPath'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['system']['Service']['SetLogLevel'](arg1);
}
