// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitInstalled() {
  return window['go']['system']['Service']['CheckGitInstalled']();
}

export function GetCurrentDataDirectory() {
  return window['go']['system']['Service']['GetCurrentDataDirectory']();
}

export function GetGitStatus() {
  return window['go']['system']['Service']['GetGitStatus']();
}

export function GetGitSyncConfig() {
  return window['go']['system']['Service']['GetGitSyncConfig']();
}

export function GetKeepInBackground() {
  return window['go']['system']['Service']['GetKeepInBackground']();
}

export function GetStartHidden() {
  return window['go']['system']['Service']['GetStartHidden']();
}

export function GetSystemInfo() {
  return window['go']['system']['Service']['GetSystemInfo']();
}

export function LogFromFrontend(arg1, arg2, arg3) {
  return window['go']['system']['Service']['LogFromFrontend'](arg1, arg2, arg3);
}

export function MigrateToGitDirectory(arg1, arg2) {
  return window['go']['system']['Service']['MigrateToGitDirectory'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['system']['Service']['OpenDirectoryDialog']();
}

export function SetContext(arg1) {
  return window['go']['system']['Service']['SetContext'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['system']['Service']['SetDBPath'](arg1);
}

export function SetGitSyncConfig(arg1) {
  return window['go']['system']['Service']['SetGitSyncConfig'](arg1);
}

export function SetKeepInBackground(arg1) {
  return window['go']['system']['Service']['SetKeepInBackground'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['system']['Service']['SetLogLevel'](arg1);
}

export function SetShutdownHandler(arg1) {
  return window['go']['system']['Service']['SetShutdownHandler'](arg1);
}

export function SetStartHidden(arg1) {
  return window['go']['system']['Service']['SetStartHidden'](arg1);
}

export function ShowWindow() {
  return window['go']['system']['Service']['ShowWindow']();
}

export function SyncNow() {
  return window['go']['system']['Service']['SyncNow']();
}

export function ValidateMigrationTarget(arg1) {
  return window['go']['system']['Service']['ValidateMigrationTarget'](arg1);
}
