// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SyncResult {
    /**
     * Creates a new SyncResult instance.
     * @param {Partial<SyncResult>} [$$source = {}] - The source object to create the SyncResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {SyncStatus}
             */
            this["status"] = SyncStatus.$zero;
        }
        if (!("filesChanged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesChanged"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["commitHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pushError"] = undefined;
        }
        if (!("pulled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pulled"] = false;
        }
        if (!("pulledFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pulledFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult(/** @type {Partial<SyncResult>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const SyncStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SyncStatusNoChanges: "no_changes",
    SyncStatusCommitted: "committed",
    SyncStatusSynced: "synced",
    SyncStatusPushFailed: "push_failed",
    SyncStatusConflict: "conflict",
    SyncStatusUpToDate: "up_to_date",
};
