// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SyncResult {
    "status": SyncStatus;
    "filesChanged": number;
    "message": string;
    "commitHash"?: string;
    "pushError"?: string;
    "pulled": boolean;
    "pulledFiles": number;

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = SyncStatus.$zero;
        }
        if (!("filesChanged" in $$source)) {
            this["filesChanged"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("pulled" in $$source)) {
            this["pulled"] = false;
        }
        if (!("pulledFiles" in $$source)) {
            this["pulledFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}

export enum SyncStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SyncStatusNoChanges = "no_changes",
    SyncStatusCommitted = "committed",
    SyncStatusSynced = "synced",
    SyncStatusPushFailed = "push_failed",
    SyncStatusConflict = "conflict",
    SyncStatusUpToDate = "up_to_date",
};
