version: '3'

# Yanta - Task Build System
# Clean, DRY architecture with separate concerns
#
# Main user-facing commands:
#   task install-tools  - Install all required tools
#   task build          - Build for current platform
#   task test           - Run all tests
#   task release:all    - Build all release artifacts
#   task dev            - Start development mode

includes:
  # Core build functionality
  build: ./build/Taskfile.yml
  # Common utilities (DRY)
  common: ./build/common/Taskfile.yml
  # Platform configurations
  platform: ./build/platform/Taskfile.yml
  # Test suite
  test: ./build/test/Taskfile.yml
  # Release management
  release: ./build/release/Taskfile.yml

vars:
  APP_NAME: "yanta"
  DEV_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  DIST_DIR: '{{.DIST_DIR | default "build/dist"}}'
  BIN_DIR: 'build/bin'

tasks:
  # ============================================================================
  # Development & Installation
  # ============================================================================

  install-tools:
    summary: Install all required development tools (wails3 CLI + frontend deps)
    cmds:
      - task: common:log:section
        vars:
          MSG: "Installing Development Tools"
      - go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - task: frontend:install
        vars:
          FORCE_CI_INSTALL: "1"
      - task: common:log:success
        vars:
          MSG: "All tools installed successfully"

  dev:
    summary: Launch Wails development mode with live reload
    deps:
      - build:ensure:wails
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.DEV_PORT}}

  # ============================================================================
  # Frontend Tasks
  # ============================================================================

  frontend:install:
    summary: Install frontend dependencies
    dir: frontend
    vars:
      FORCE_CI_INSTALL: '{{.FORCE_CI_INSTALL | default "0"}}'
    cmds:
      - |
        if [ "{{.FORCE_CI_INSTALL}}" = "1" ] || [ "${CI:-}" = "true" ]; then
          npm ci
        else
          npm install
        fi

  frontend:build:
    summary: Build the frontend bundle
    deps:
      - frontend:install
      - bindings
    dir: frontend
    cmds:
      - npm run build

  frontend:typecheck:
    summary: Run frontend TypeScript type checking
    cmds:
      - task: test:frontend:typecheck

  frontend:dev:
    summary: Run frontend dev server
    cmds:
      - task: build:dev:frontend

  # ============================================================================
  # Bindings
  # ============================================================================

  bindings:
    summary: Generate TypeScript bindings from Go services
    cmds:
      - task: build:generate:bindings

  # ============================================================================
  # Build Commands (Platform-specific)
  # ============================================================================

  build:
    summary: Build application for current platform (auto-detect) or specified TARGET
    vars:
      TARGET: '{{.TARGET | default "local"}}'
      DEBUG: '{{.DEBUG | default "0"}}'
    deps:
      - bindings
      - frontend:build
    cmds:
      - task: build:go:build
        vars:
          TARGET: '{{.TARGET}}'
          DEBUG: '{{.DEBUG}}'

  build:win:
    summary: Build for Windows (requires Windows or Linux with MinGW)
    deps:
      - bindings
      - frontend:build
    cmds:
      - task: build:go:build
        vars:
          TARGET: win

  build:linux:
    summary: Build for Linux/Ubuntu
    deps:
      - bindings
      - frontend:build
    cmds:
      - task: build:go:build
        vars:
          TARGET: ubuntu

  build:arch:
    summary: Build for Arch Linux (includes tarball + package generation)
    deps:
      - bindings
      - frontend:build
    cmds:
      - task: build:go:build
        vars:
          TARGET: arch

  build:osx:
    summary: Build for macOS
    deps:
      - bindings
      - frontend:build
    cmds:
      - task: build:go:build
        vars:
          TARGET: osx

  # ============================================================================
  # Run & Package
  # ============================================================================

  run:
    summary: Run the last built binary (builds first if needed)
    deps:
      - build
    cmds:
      - |
        if [ "$OS" = "Windows_NT" ]; then
          ./{{.BIN_DIR}}/{{.APP_NAME}}.exe
        else
          ./{{.BIN_DIR}}/{{.APP_NAME}}
        fi

  package:
    summary: Build release artifacts for current platform
    cmds:
      - task: release:all

  # ============================================================================
  # Testing
  # Note: Test tasks are available via the `test` namespace
  # Examples:
  #   task test:all           - Run all tests (backend + frontend + lint)
  #   task test:backend       - Run backend tests with coverage
  #   task test:frontend      - Run frontend typecheck
  #   task test:lint          - Run all linters
  #   task test:backend:coverage-html - Generate HTML coverage report
  # ============================================================================

  # Convenience aliases for common test commands
  test:
    summary: Run all tests (backend + frontend + lint)
    cmds:
      - task: test:all

  lint:
    summary: Run all linters (Go + frontend)
    cmds:
      - task: test:lint

  # ============================================================================
  # Release Management
  # Note: Release tasks are available via the `release` namespace
  # Examples: task release:linux, task release:ubuntu, task release:all
  # ============================================================================

  # ============================================================================
  # Utilities
  # ============================================================================

  clean:
    summary: Clean all build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf {{.DIST_DIR}}
      - rm -rf .gocache
      - task: test:clean
      - task: common:log:success
        vars:
          MSG: "All build artifacts cleaned"

  version:
    summary: Show current version
    cmds:
      - task: common:version:get

  info:
    summary: Show build information
    vars:
      VERSION:
        sh: git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || git rev-parse --short HEAD 2>/dev/null | sed 's/^/dev-/' || echo "unknown"
      COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
      PLATFORM:
        sh: uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' || echo "unknown"
    cmds:
      - |
        echo "Yanta Build System"
        echo "=================="
        echo ""
        echo "App Name:     {{.APP_NAME}}"
        echo "Version:      {{.VERSION}}"
        echo "Commit:       {{.COMMIT}}"
        echo "Platform:     {{.PLATFORM}}"
        echo ""
        echo "Directories:"
        echo "  Binary:     {{.BIN_DIR}}"
        echo "  Dist:       {{.DIST_DIR}}"
        echo ""
        echo "Use 'task --list' to see all available commands"

  # ============================================================================
  # CI-specific Commands
  # ============================================================================

  ci:test:
    summary: Run tests in CI mode
    cmds:
      - task: test:ci

  ci:build:
    summary: Build for CI (current platform)
    cmds:
      - task: build

  ci:release:
    summary: Build release artifacts for CI
    cmds:
      - task: release:all
      - task: release:list

  # ============================================================================
  # Help
  # ============================================================================

  help:
    summary: Show help information
    silent: true
    cmds:
      - |
        cat <<'EOF'
        Yanta Task Build System
        ======================

        Common Commands:
          task install-tools      Install all required development tools
          task dev                Start development mode with hot reload
          task build              Build for current platform
          task test               Run all tests
          task release:all        Build all release artifacts

        Build Commands:
          task build:win          Build for Windows
          task build:linux        Build for Linux/Ubuntu
          task build:arch         Build for Arch Linux
          task build:osx          Build for macOS

        Test Commands:
          task test               Run all tests
          task test:backend       Run backend tests
          task test:frontend      Run frontend tests
          task lint               Run linters

        Release Commands:
          task release:linux      Build Linux artifacts (tarball + Arch)
          task release:ubuntu     Build Ubuntu/Debian .deb package
          task release:windows    Build Windows artifacts (portable + installer)
          task release:macos      Build macOS tarball
          task release:list       List generated artifacts
          task release:clean      Clean release artifacts

        Utility Commands:
          task clean              Clean all build artifacts
          task version            Show current version
          task info               Show build information
          task --list             List all available tasks

        For more details, run: task --list
        EOF
