version: '3'

# Yanta - Task Build System
# Clean, DRY architecture with separate concerns
#
# Main user-facing commands:
#   task install-tools  - Install all required tools
#   task build          - Build for current platform
#   task test           - Run all tests
#   task release:all    - Build all release artifacts
#   task dev            - Start development mode

includes:
  # Core build functionality
  build: ./build/Taskfile.yml
  # Common utilities (DRY)
  common: ./build/common/Taskfile.yml
  # Platform configurations
  platform: ./build/platform/Taskfile.yml
  # Test suite
  test: ./build/test/Taskfile.yml
  # Release management
  release: ./build/release/Taskfile.yml

vars:
  APP_NAME: "yanta"
  DEV_PORT: '{{.WAILS_VITE_PORT | default 34115}}'
  DIST_DIR: '{{.DIST_DIR | default "build/dist"}}'
  BIN_DIR: 'build/bin'

set:
  - nounset
  - errexit
  - pipefail

output: interleaved  # Changed from 'group' to get real-time output

silent: false

tasks:
  # ============================================================================
  # Development & Installation
  # ============================================================================

  install-tools:
    summary: Install all required development tools (wails3 CLI + frontend deps)
    cmds:
      - task: common:log:section
        vars:
          MSG: "Installing Development Tools"
      - go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - task: frontend:install
        vars:
          FORCE_CI_INSTALL: "1"
      - task: common:log:success
        vars:
          MSG: "All tools installed successfully"

  dev:
    summary: Launch Wails development mode with live reload
    deps:
      - build:ensure:wails
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.DEV_PORT}}

  # ============================================================================
  # Frontend Tasks
  # ============================================================================

  frontend:install:
    summary: Install frontend dependencies (cross-platform)
    desc: |
      Installs frontend npm dependencies. Uses 'npm ci' for clean installs in CI
      environments or when FORCE_CI_INSTALL=1, otherwise uses 'npm install'.
      Cross-platform: Works in both Windows PowerShell and Unix shells.
    dir: frontend
    silent: true
    deps:
      - common:ensure:npm
    vars:
      # FORCE_CI_INSTALL can be set to "1" to force npm ci (e.g., in install-tools)
      FORCE_CI_INSTALL: '{{.FORCE_CI_INSTALL | default "0"}}'
    cmds:
      # Cross-platform: PowerShell on Windows, POSIX shell on Unix
      # Uses npm ci when FORCE_CI_INSTALL=1 or CI=true, otherwise npm install
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command "if ('{{.FORCE_CI_INSTALL}}' -eq '1' -or $env:CI -eq 'true') { npm ci } else { npm install }"
        {{else}}
        if [ "{{.FORCE_CI_INSTALL}}" = "1" ] || [ "${CI:-}" = "true" ]; then
          npm ci
        else
          npm install
        fi
        {{end}}

  frontend:build:
    label: "build:frontend (PRODUCTION={{.PRODUCTION}})"
    summary: Build the frontend bundle
    deps:
      - frontend:install
      - bindings
    dir: frontend
    sources:
      - "src/**/*"
      - "index.html"
      - "package.json"
      - "vite.config.ts"
      - "tsconfig.json"
      - "tsconfig.node.json"
      - "bindings/**/*"
    generates:
      - "dist/**/*"
    vars:
      BUILD_COMMAND: '{{if eq .PRODUCTION "true"}}build{{else}}build:dev{{end}}'
    env:
      PRODUCTION: '{{.PRODUCTION | default "false"}}'
    cmds:
      - npm run {{.BUILD_COMMAND}}

  frontend:typecheck:
    summary: Run frontend TypeScript type checking
    cmds:
      - task: test:frontend:typecheck

  frontend:dev:
    summary: Run frontend dev server
    cmds:
      - task: build:dev:frontend

  # ============================================================================
  # Bindings
  # ============================================================================

  bindings:
    summary: Generate TypeScript bindings from Go services
    cmds:
      - task: build:generate:bindings

  icons:
    summary: Generate platform icons from appicon.png
    cmds:
      - task: build:generate:icons

  # ============================================================================
  # Build Commands (Platform-specific)
  # ============================================================================

  build:
    label: "build (TARGET={{.TARGET}}, PRODUCTION={{.PRODUCTION}})"
    summary: Build application for current platform (auto-detect) or specified TARGET
    silent: true
    vars:
      TARGET: '{{.TARGET | default "local"}}'
      DEBUG: '{{.DEBUG | default "0"}}'
      PRODUCTION: '{{.PRODUCTION | default "false"}}'
    deps:
      - task: frontend:build
        vars:
          PRODUCTION: '{{.PRODUCTION}}'
    cmds:
      - task: build:go:build
        vars:
          TARGET: '{{.TARGET}}'
          DEBUG: '{{.DEBUG}}'

  build:win:
    label: "build:win (PRODUCTION={{.PRODUCTION}})"
    summary: Build for Windows (requires Windows or Linux with MinGW)
    vars:
      PRODUCTION: '{{.PRODUCTION | default "true"}}'
    deps:
      - task: frontend:build
        vars:
          PRODUCTION: '{{.PRODUCTION}}'
    cmds:
      - task: build:go:build
        vars:
          TARGET: win

  build:linux:
    label: "build:linux (PRODUCTION={{.PRODUCTION}})"
    summary: Build for Linux/Ubuntu
    vars:
      PRODUCTION: '{{.PRODUCTION | default "true"}}'
    deps:
      - task: frontend:build
        vars:
          PRODUCTION: '{{.PRODUCTION}}'
    cmds:
      - task: build:go:build
        vars:
          TARGET: ubuntu

  build:arch:
    label: "build:arch (PRODUCTION={{.PRODUCTION}})"
    summary: Build for Arch Linux
    vars:
      PRODUCTION: '{{.PRODUCTION | default "true"}}'
    deps:
      - task: frontend:build
        vars:
          PRODUCTION: '{{.PRODUCTION}}'
    cmds:
      - task: build:go:build
        vars:
          TARGET: arch

  build:osx:
    label: "build:osx (PRODUCTION={{.PRODUCTION}})"
    summary: Build for macOS
    vars:
      PRODUCTION: '{{.PRODUCTION | default "true"}}'
    deps:
      - task: frontend:build
        vars:
          PRODUCTION: '{{.PRODUCTION}}'
    cmds:
      - task: build:go:build
        vars:
          TARGET: osx

  # ============================================================================
  # Run & Package
  # ============================================================================

  run:
    summary: Run the last built binary (builds first if needed)
    desc: |
      Executes the built application binary for the current platform.
      Cross-platform: Automatically uses .exe extension on Windows.
      Uses Taskfile {{OS}} for platform detection instead of bash environment variables.
    silent: true
    vars:
      # Cross-platform executable extension
      EXE_EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'
    cmds:
      # Cross-platform: Uses Taskfile template for correct binary path
      - ./{{.BIN_DIR}}/{{.APP_NAME}}{{.EXE_EXT}}

  package:
    summary: Build release artifacts for current platform
    cmds:
      - task: release:all

  # ============================================================================
  # Testing
  # Note: Test tasks are available via the `test` namespace
  # Examples:
  #   task test:all           - Run all tests (backend + frontend + lint)
  #   task test:backend       - Run backend tests with coverage
  #   task test:frontend      - Run frontend typecheck
  #   task test:lint          - Run all linters
  #   task test:backend:coverage-html - Generate HTML coverage report
  # ============================================================================

  # Convenience aliases for common test commands
  test:
    summary: Run all tests (backend + frontend + lint)
    cmds:
      - task: test:all

  lint:
    summary: Run all linters (Go + frontend)
    cmds:
      - task: test:lint

  # ============================================================================
  # Release Management
  # Note: Release tasks are available via the `release` namespace
  # Examples: task release:linux, task release:ubuntu, task release:all
  # ============================================================================

  # ============================================================================
  # Utilities
  # ============================================================================

  clean:
    summary: Clean all build artifacts (cross-platform)
    desc: |
      Removes all build artifacts including binaries, dist files, and caches.
      Cross-platform: Works in both Windows PowerShell and Unix shells.
    cmds:
      # Cross-platform rm -rf: PowerShell on Windows, rm -rf on Unix
      - '{{if eq OS "windows"}}powershell -NoProfile -Command "if (Test-Path ''{{.BIN_DIR}}'') { Remove-Item -Recurse -Force ''{{.BIN_DIR}}'' }"{{else}}rm -rf "{{.BIN_DIR}}"{{end}}'
      - '{{if eq OS "windows"}}powershell -NoProfile -Command "if (Test-Path ''{{.DIST_DIR}}'') { Remove-Item -Recurse -Force ''{{.DIST_DIR}}'' }"{{else}}rm -rf "{{.DIST_DIR}}"{{end}}'
      - '{{if eq OS "windows"}}powershell -NoProfile -Command "if (Test-Path ''.gocache'') { Remove-Item -Recurse -Force ''.gocache'' }"{{else}}rm -rf ".gocache"{{end}}'
      - task: test:clean
      - task: common:log:success
        vars:
          MSG: "All build artifacts cleaned"

  version:
    summary: Show current version
    cmds:
      - task: common:version:get

  info:
    summary: Show build information (cross-platform)
    desc: |
      Displays build system information including app name, version, commit hash,
      and platform. Cross-platform: Works in both Windows PowerShell and Unix shells.
      Uses Taskfile {{OS}} for platform detection instead of uname.
    silent: true
    cmds:
      # Cross-platform: PowerShell on Windows, POSIX shell on Unix
      # Uses Taskfile {{OS}} for platform and git commands for version/commit
      - |
        {{if eq OS "windows"}}
        powershell -NoProfile -Command @"
        `$ErrorActionPreference = 'SilentlyContinue'

        # Get version: YANTA_VERSION > git tag > dev-commit
        `$commit = (git rev-parse --short HEAD 2>`$null)
        if (-not `$commit) { `$commit = 'unknown' }

        `$version = `$env:YANTA_VERSION
        if (-not `$version) {
          `$tag = (git describe --tags --abbrev=0 2>`$null)
          if (`$tag) {
            `$version = `$tag -replace '^v', ''
          } else {
            `$version = "dev-`$commit"
          }
        }

        Write-Host 'Yanta Build System'
        Write-Host '=================='
        Write-Host ''
        Write-Host "App Name:     {{.APP_NAME}}"
        Write-Host "Version:      `$version"
        Write-Host "Commit:       `$commit"
        Write-Host 'Platform:     {{OS}}'
        Write-Host ''
        Write-Host 'Directories:'
        Write-Host "  Binary:     {{.BIN_DIR}}"
        Write-Host "  Dist:       {{.DIST_DIR}}"
        Write-Host ''
        Write-Host "Use 'task --list' to see all available commands"
        "@
        {{else}}
        # Get commit hash
        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

        # Get version: YANTA_VERSION > git tag > dev-commit
        if [ -n "${YANTA_VERSION:-}" ]; then
          VERSION="${YANTA_VERSION}"
        elif VERSION_TAG=$(git describe --tags --abbrev=0 2>/dev/null); then
          VERSION="${VERSION_TAG#v}"
        else
          VERSION="dev-${COMMIT}"
        fi

        echo "Yanta Build System"
        echo "=================="
        echo ""
        echo "App Name:     {{.APP_NAME}}"
        echo "Version:      ${VERSION}"
        echo "Commit:       ${COMMIT}"
        echo "Platform:     {{OS}}"
        echo ""
        echo "Directories:"
        echo "  Binary:     {{.BIN_DIR}}"
        echo "  Dist:       {{.DIST_DIR}}"
        echo ""
        echo "Use 'task --list' to see all available commands"
        {{end}}

  # ============================================================================
  # CI-specific Commands
  # ============================================================================

  ci:test:
    summary: Run tests in CI mode
    cmds:
      - task: test:ci

  ci:build:
    summary: Build for CI (current platform)
    cmds:
      - task: build

  ci:release:
    summary: Build release artifacts for CI
    cmds:
      - task: release:all
      - task: release:list

  # ============================================================================
  # Help
  # ============================================================================

  help:
    summary: Show help information
    silent: true
    cmds:
      - |
        cat <<'EOF'
        Yanta Task Build System
        ======================

        Common Commands:
          task install-tools      Install all required development tools
          task dev                Start development mode with hot reload
          task build              Build for current platform
          task test               Run all tests
          task release:all        Build all release artifacts

        Build Commands:
          task build:win          Build for Windows
          task build:linux        Build for Linux/Ubuntu
          task build:arch         Build for Arch Linux
          task build:osx          Build for macOS

        Test Commands:
          task test               Run all tests
          task test:backend       Run backend tests
          task test:frontend      Run frontend tests
          task lint               Run linters

        Release Commands:
          task release:linux      Build Linux artifacts (tarball + Arch)
          task release:ubuntu     Build Ubuntu/Debian .deb package
          task release:windows    Build Windows artifacts (portable + installer)
          task release:macos      Build macOS tarball
          task release:list       List generated artifacts
          task release:clean      Clean release artifacts

        Utility Commands:
          task clean              Clean all build artifacts
          task version            Show current version
          task info               Show build information
          task --list             List all available tasks

        For more details, run: task --list
        EOF
