version: '3'

includes:
  common: ./build/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "yanta"
  DEV_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  WAILS_PLATFORM: '{{.PLATFORM | default .WAILS_PLATFORM}}'
  WAILS_FLAGS: '{{.FLAGS | default ""}}'
  DIST_DIR: '{{.DIST_DIR | default "build/dist"}}'

tasks:
  install-tools:
    summary: Install required development toolchain (wails3 CLI + frontend deps)
    cmds:
      - go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - task: frontend:install
        vars:
          FORCE_CI_INSTALL: "1"

  bindings:
    summary: Generate TypeScript bindings using wails3
    deps:
      - task: common:generate:bindings

  frontend:install:
    summary: Install frontend dependencies
    dir: frontend
    vars:
      FORCE_CI_INSTALL: '{{.FORCE_CI_INSTALL | default "0"}}'
    cmds:
      - |
          if [ "{{.FORCE_CI_INSTALL}}" = "1" ] || [ "${CI:-}" = "true" ]; then
            npm ci
          else
            npm install
          fi

  frontend:build:
    summary: Build the frontend bundle
    deps:
      - frontend:install
      - bindings
    dir: frontend
    cmds:
      - npm run build

  frontend:typecheck:
    summary: Run frontend type checking
    deps:
      - frontend:install
      - bindings
    dir: frontend
    cmds:
      - npx tsc --noEmit

  build:
    summary: Build the application (override TARGET=win|ubuntu|arch|osx)
    vars:
      TARGET: '{{.TARGET | default "local"}}'
      DEBUG: '{{.DEBUG | default "0"}}'
    cmds:
      - task: internal:go-build
        vars:
          TARGET: '{{.TARGET}}'
          DEBUG: '{{.DEBUG}}'

  build:win:
    summary: Build Windows binaries
    cmds:
      - task: build
        vars:
          TARGET: win

  build:linux:
    summary: Build Linux binaries
    cmds:
      - task: build
        vars:
          TARGET: ubuntu

  build:arch:
    summary: Cross-build for Linux and produce tar/pkg artifacts
    cmds:
      - task: build
        vars:
          TARGET: arch

  build:osx:
    summary: Build macOS binaries
    cmds:
      - task: build
        vars:
          TARGET: osx

  run:
    summary: Run the last built binary (builds first if needed)
    deps:
      - build
    cmds:
      - |
        if [ "$OS" = "Windows_NT" ]; then
          ./build/bin/{{.APP_NAME}}.exe
        else
          ./build/bin/{{.APP_NAME}}
        fi

  dev:
    summary: Launch Wails dev mode with live reload
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.DEV_PORT}}

  package:
    summary: Build release artifacts for the host platform
    cmds:
      - task: build

  internal:go-build:
    internal: true
    deps:
      - bindings
      - frontend:build
    vars:
      TARGET: '{{.TARGET | default "local"}}'
      DEBUG: '{{.DEBUG | default "0"}}'
    cmds:
      - |
        bash <<'EOF'
        set -euo pipefail

        GO_CACHE_DIR="${GO_CACHE_DIR:-.gocache}"
        case "$GO_CACHE_DIR" in
          /*) ;;
          *) GO_CACHE_DIR="$(pwd)/$GO_CACHE_DIR" ;;
        esac
        mkdir -p "$GO_CACHE_DIR"
        export GOCACHE="$GO_CACHE_DIR"

        TARGET="{{.TARGET}}"
        DEBUG="{{.DEBUG}}"

        require_cmd() {
          if ! command -v "$1" >/dev/null 2>&1; then
            echo "Error: '$1' is not installed or not in PATH." >&2
            exit 1
          fi
        }

        ensure_host() {
          local required="$1"
          local host
          host=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$required" in
            darwin)
              if [[ "$host" != "darwin" ]]; then
                echo "This target must be built on macOS (current host: $host)" >&2
                exit 1
              fi
              ;;
            linux)
              if [[ "$host" != "linux" ]]; then
                echo "This target must be built on Linux (current host: $host)" >&2
                exit 1
              fi
              ;;
          esac
        }

        ensure_mingw() {
          if command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1 && command -v x86_64-w64-mingw32-g++ >/dev/null 2>&1; then
            return
          fi

          if command -v apt-get >/dev/null 2>&1; then
            echo "Installing MinGW toolchain (mingw-w64)..."
            sudo apt-get update
            sudo apt-get install -y mingw-w64
          else
            echo "MinGW toolchain not found (x86_64-w64-mingw32-gcc). Install it manually." >&2
            exit 1
          fi
        }

        require_cmd go
        require_cmd npm
        require_cmd python3

        HOST_UNAME=$(uname -s | tr '[:upper:]' '[:lower:]')

        if [[ -z "$TARGET" || "$TARGET" == "local" ]]; then
          case "$HOST_UNAME" in
            linux)
              TARGET="ubuntu"
              ;;
            darwin)
              TARGET="osx"
              ;;
            *mingw*|*msys*|*cygwin*|windows)
              TARGET="win"
              ;;
            *)
              TARGET="ubuntu"
              ;;
          esac
        fi

        USE_WEBKIT41=false
        POST_BUILD=""
        GOOS_TARGET=""
        GOARCH_TARGET="amd64"
        CC_OVERRIDE=""
        CXX_OVERRIDE=""
        OUTPUT_SUFFIX=""

        case "$TARGET" in
          win|windows)
            GOOS_TARGET="windows"
            OUTPUT_SUFFIX=".exe"
            if [[ "$HOST_UNAME" == "linux" ]]; then
              echo "Building Windows target on Linux requires MinGW (x86_64-w64-mingw32) toolchain..."
              ensure_mingw
              require_cmd x86_64-w64-mingw32-gcc
              require_cmd x86_64-w64-mingw32-g++
              CC_OVERRIDE="x86_64-w64-mingw32-gcc"
              CXX_OVERRIDE="x86_64-w64-mingw32-g++"
            elif [[ "$HOST_UNAME" == *mingw* || "$HOST_UNAME" == *msys* || "$HOST_UNAME" == *cygwin* || "$HOST_UNAME" == "windows" ]]; then
              GOOS_TARGET=""
            else
              echo "Windows builds must run on Windows or Linux (with MinGW installed)." >&2
              exit 1
            fi
            ;;
          ubuntu)
            ensure_host linux
            GOOS_TARGET="linux"
            USE_WEBKIT41=true
            ;;
          arch)
            ensure_host linux
            GOOS_TARGET="linux"
            USE_WEBKIT41=true
            POST_BUILD="arch"
            ;;
          osx|mac|macos)
            ensure_host darwin
            GOOS_TARGET="darwin"
            ;;
          *)
            echo "Unknown target: $TARGET" >&2
            exit 1
            ;;
        esac

        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        if [[ -n "${YANTA_VERSION:-}" ]]; then
          VERSION="${YANTA_VERSION}"
        elif VERSION_TAG=$(git describe --tags --abbrev=0 2>/dev/null); then
          VERSION="${VERSION_TAG#v}"
        else
          VERSION="dev-${COMMIT}"
        fi
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        LD_FLAGS="-X yanta/internal/system.BuildVersion=${VERSION} -X yanta/internal/system.BuildCommit=${COMMIT} -X yanta/internal/system.BuildDate=${DATE}"

        echo "Compiling Go binary for target '${TARGET}'..."
        mkdir -p build/bin
        OUTPUT_PATH="build/bin/{{.APP_NAME}}${OUTPUT_SUFFIX}"

        BUILD_ENV=()
        if [[ -n "$GOOS_TARGET" ]]; then
          BUILD_ENV+=(GOOS="$GOOS_TARGET")
        fi
        BUILD_ENV+=(GOARCH="$GOARCH_TARGET")
        if [[ -n "$CC_OVERRIDE" ]]; then
          BUILD_ENV+=(CC="$CC_OVERRIDE" CXX="$CXX_OVERRIDE" CGO_ENABLED=1)
        fi

        BUILD_TAGS=()
        if $USE_WEBKIT41; then
          BUILD_TAGS+=("-tags" "webkit2_41")
        fi

        if [[ "$DEBUG" == "1" ]]; then
          export YANTA_DEBUG_BUILD=1
        fi

        env "${BUILD_ENV[@]}" go build "${BUILD_TAGS[@]}" -ldflags "$LD_FLAGS" -o "$OUTPUT_PATH" .

        if [[ "$POST_BUILD" == "arch" ]]; then
          echo "Packaging Linux artifacts (Arch + tarball)..."
          scripts/build_linux_artifacts.sh "$VERSION" "1"
          echo "Artifacts written to build/dist/"
        fi

        echo "Artifacts available under build/bin/"
        EOF

  test:backend:
    summary: Run Go unit tests with race detector and coverage
    cmds:
      - |
        bash <<'EOF'
        set -euo pipefail
        GO_CACHE_DIR="${GO_CACHE_DIR:-.gocache}"
        case "$GO_CACHE_DIR" in
          /*) ;;
          *) GO_CACHE_DIR="$(pwd)/$GO_CACHE_DIR" ;;
        esac
        mkdir -p "$GO_CACHE_DIR"
        GOCACHE="$GO_CACHE_DIR" go test -v -race -coverprofile=coverage.out ./...
        EOF

  release:linux:
    summary: Build Linux release artifacts (tarball + Arch package)
    deps:
      - build:arch
    cmds:
      - |
        set -euo pipefail
        if [ ! -d "{{.DIST_DIR}}" ]; then
          echo "Expected artifacts under {{.DIST_DIR}}, but directory is missing" >&2
          exit 1
        fi
        ls -1 {{.DIST_DIR}}/yanta-linux.tar.gz {{.DIST_DIR}}/yanta-*-x86_64.pkg.tar.gz >/dev/null
        echo "Linux artifacts ready under {{.DIST_DIR}}"

  release:ubuntu:
    summary: Build Ubuntu/Debian .deb package from the Linux tarball
    deps:
      - release:linux
    cmds:
      - |
        set -euo pipefail
        TAR="{{.DIST_DIR}}/yanta-linux.tar.gz"
            if [ ! -f "$TAR" ]; then
              echo "Linux tarball not found at $TAR. Run 'task release:linux' first." >&2
              exit 1
            fi
            if [ -n "${YANTA_VERSION:-}" ]; then
              VERSION="${YANTA_VERSION}"
            elif git describe --tags --abbrev=0 >/dev/null 2>&1; then
              VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
            else
              COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
              VERSION="dev-${COMMIT}"
            fi
        scripts/build_deb_from_tar.sh "$TAR" "$VERSION"

  release:windows:
    summary: Build Windows release artifacts (portable + installer)
    deps:
      - build:win
    cmds:
      - |
        set -euo pipefail
        DIST="{{.DIST_DIR}}"
        rm -rf "$DIST"
        mkdir -p "$DIST"

        PORTABLE="build/bin/{{.APP_NAME}}.exe"
        if [ ! -f "$PORTABLE" ]; then
          echo "Portable binary not found at $PORTABLE" >&2
          exit 1
        fi
        cp "$PORTABLE" "$DIST/yanta-windows-portable.exe"

        INSTALLER=$(find build/bin -maxdepth 1 -type f -iname '*installer*.exe' -print -quit)
        if [ -z "$INSTALLER" ]; then
          echo 'Could not locate the NSIS installer output in build/bin' >&2
          exit 1
        fi
        cp "$INSTALLER" "$DIST/yanta-windows-installer.exe"

  release:macos:
    summary: Build macOS release tarball
    deps:
      - build:osx
    cmds:
      - cmd: bash
        args:
          - -lc
          - |
            set -euo pipefail
            DIST="{{.DIST_DIR}}"
            rm -rf "$DIST"
            mkdir -p "$DIST"
            tar -C build/bin -czf "$DIST/yanta-macos.tar.gz" yanta.app

  release:all:
    summary: Build release artifacts supported on the current host
    cmds:
      - task: release:all:linux
      - task: release:all:windows
      - task: release:all:mac

  release:all:linux:
    internal: true
    platforms: [linux]
    cmds:
      - task: release:linux
      - task: release:ubuntu

  release:all:windows:
    internal: true
    platforms: [windows]
    cmds:
      - task: release:windows

  release:all:mac:
    internal: true
    platforms: [darwin]
    cmds:
      - task: release:macos
