// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateBackup creates a timestamped backup of the data directory
 * @param {string} dataDir
 * @returns {$CancellablePromise<void>}
 */
export function CreateBackup(dataDir) {
    return $Call.ByID(2575318254, dataDir);
}

/**
 * Delete deletes a specific backup
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function Delete(backupPath) {
    return $Call.ByID(4203185055, backupPath);
}

/**
 * DeleteBackup deletes a specific backup
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBackup(backupPath) {
    return $Call.ByID(2800067461, backupPath);
}

/**
 * GetBackups returns a list of available backups for the frontend
 * @returns {$CancellablePromise<$models.BackupInfo[]>}
 */
export function GetBackups() {
    return $Call.ByID(111509975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfig returns the current backup configuration
 * @returns {$CancellablePromise<config$0.BackupConfig>}
 */
export function GetConfig() {
    return $Call.ByID(457937118).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListBackups returns a list of available backups, sorted by timestamp (newest first)
 * @param {string} dataDir
 * @returns {$CancellablePromise<$models.BackupInfo[]>}
 */
export function ListBackups(dataDir) {
    return $Call.ByID(3780049603, dataDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PruneOldBackups removes old backups keeping only maxBackups most recent ones
 * @param {string} dataDir
 * @param {number} maxBackups
 * @returns {$CancellablePromise<void>}
 */
export function PruneOldBackups(dataDir, maxBackups) {
    return $Call.ByID(470099688, dataDir, maxBackups);
}

/**
 * Restore restores data from a specific backup
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function Restore(backupPath) {
    return $Call.ByID(517804990, backupPath);
}

/**
 * RestoreBackup restores data from a backup
 * @param {string} dataDir
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function RestoreBackup(dataDir, backupPath) {
    return $Call.ByID(4084337592, dataDir, backupPath);
}

/**
 * SetConfig updates the backup configuration
 * @param {config$0.BackupConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(cfg) {
    return $Call.ByID(2740971594, cfg);
}

// Private type creation functions
const $$createType0 = $models.BackupInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.BackupConfig.createFrom;
