// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetBackups(): $CancellablePromise<$models.BackupInfo[]> {
	return $Call.ByID(0).then(($result: any) => {
		return $$createType0($result);
	});
}

export function Restore(backupPath: string): $CancellablePromise<void> {
	return $Call.ByID(0, backupPath);
}

export function Delete(backupPath: string): $CancellablePromise<void> {
	return $Call.ByID(0, backupPath);
}

export function GetConfig(): $CancellablePromise<$models.BackupConfig> {
	return $Call.ByID(0).then(($result: any) => {
		return $$createType1($result);
	});
}

export function SetConfig(cfg: $models.BackupConfig): $CancellablePromise<void> {
	return $Call.ByID(0, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($models.BackupInfo.createFrom);
const $$createType1 = $models.BackupConfig.createFrom;
