// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsService from "./wailsservice.js";
export {
    WailsService
};

export {
    AppendEntryRequest,
    AppendEntryRequestWithDate,
    JournalEntry,
    JournalEntryWithProject,
    JournalFile,
    JournalMeta,
    PromoteRequest,
    SearchResult,
    UpdateEntryRequest
} from "./models.js";
