// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * AppendEntryRequest is the request for adding a new journal entry.
 */
export class AppendEntryRequest {
    /**
     * Creates a new AppendEntryRequest instance.
     * @param {Partial<AppendEntryRequest>} [$$source = {}] - The source object to create the AppendEntryRequest.
     */
    constructor($$source = {}) {
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendEntryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppendEntryRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new AppendEntryRequest(/** @type {Partial<AppendEntryRequest>} */($$parsedSource));
    }
}

/**
 * AppendEntryRequestWithDate allows specifying a date for backdated entries.
 */
export class AppendEntryRequestWithDate {
    /**
     * Creates a new AppendEntryRequestWithDate instance.
     * @param {Partial<AppendEntryRequestWithDate>} [$$source = {}] - The source object to create the AppendEntryRequestWithDate.
     */
    constructor($$source = {}) {
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendEntryRequestWithDate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppendEntryRequestWithDate}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new AppendEntryRequestWithDate(/** @type {Partial<AppendEntryRequestWithDate>} */($$parsedSource));
    }
}

/**
 * JournalEntry represents a single quick capture entry in a daily journal.
 */
export class JournalEntry {
    /**
     * Creates a new JournalEntry instance.
     * @param {Partial<JournalEntry>} [$$source = {}] - The source object to create the JournalEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["deleted"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new JournalEntry(/** @type {Partial<JournalEntry>} */($$parsedSource));
    }
}

/**
 * JournalEntryWithProject wraps a JournalEntry with its project alias.
 * Used when fetching entries from all projects.
 */
export class JournalEntryWithProject {
    /**
     * Creates a new JournalEntryWithProject instance.
     * @param {Partial<JournalEntryWithProject>} [$$source = {}] - The source object to create the JournalEntryWithProject.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["deleted"] = undefined;
        }
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalEntryWithProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalEntryWithProject}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new JournalEntryWithProject(/** @type {Partial<JournalEntryWithProject>} */($$parsedSource));
    }
}

/**
 * JournalFile represents a daily journal file containing multiple entries.
 */
export class JournalFile {
    /**
     * Creates a new JournalFile instance.
     * @param {Partial<JournalFile>} [$$source = {}] - The source object to create the JournalFile.
     */
    constructor($$source = {}) {
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {JournalMeta}
             */
            this["meta"] = (new JournalMeta());
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {JournalEntry[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalFile}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new JournalFile(/** @type {Partial<JournalFile>} */($$parsedSource));
    }
}

/**
 * JournalMeta contains metadata for a daily journal file.
 */
export class JournalMeta {
    /**
     * Creates a new JournalMeta instance.
     * @param {Partial<JournalMeta>} [$$source = {}] - The source object to create the JournalMeta.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalMeta(/** @type {Partial<JournalMeta>} */($$parsedSource));
    }
}

/**
 * PromoteRequest is the request for promoting entries to a document.
 */
export class PromoteRequest {
    /**
     * Creates a new PromoteRequest instance.
     * @param {Partial<PromoteRequest>} [$$source = {}] - The source object to create the PromoteRequest.
     */
    constructor($$source = {}) {
        if (!("sourceProject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceProject"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("entryIds" in $$source)) {
            /**
             * empty means whole day
             * @member
             * @type {string[]}
             */
            this["entryIds"] = [];
        }
        if (!("targetProject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetProject"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("keepOriginal" in $$source)) {
            /**
             * true = copy, false = move
             * @member
             * @type {boolean}
             */
            this["keepOriginal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromoteRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromoteRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entryIds" in $$parsedSource) {
            $$parsedSource["entryIds"] = $$createField2_0($$parsedSource["entryIds"]);
        }
        return new PromoteRequest(/** @type {Partial<PromoteRequest>} */($$parsedSource));
    }
}

/**
 * SearchResult represents a journal entry search result.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {JournalEntry}
             */
            this["entry"] = (new JournalEntry());
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField2_0($$parsedSource["entry"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * UpdateEntryRequest is the request for updating an existing entry.
 */
export class UpdateEntryRequest {
    /**
     * Creates a new UpdateEntryRequest instance.
     * @param {Partial<UpdateEntryRequest>} [$$source = {}] - The source object to create the UpdateEntryRequest.
     */
    constructor($$source = {}) {
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("entryId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entryId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * nil means keep existing
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateEntryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateEntryRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new UpdateEntryRequest(/** @type {Partial<UpdateEntryRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = JournalMeta.createFrom;
const $$createType2 = JournalEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
