// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * AppendEntryRequest is the request for adding a new journal entry.
 */
export class AppendEntryRequest {
    "projectAlias": string;
    "content": string;
    "tags": string[];

    /** Creates a new AppendEntryRequest instance. */
    constructor($$source: Partial<AppendEntryRequest> = {}) {
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendEntryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendEntryRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new AppendEntryRequest($$parsedSource as Partial<AppendEntryRequest>);
    }
}

/**
 * AppendEntryRequestWithDate allows specifying a date for backdated entries.
 */
export class AppendEntryRequestWithDate {
    "projectAlias": string;
    "content": string;
    "tags": string[];
    "date": string;

    /** Creates a new AppendEntryRequestWithDate instance. */
    constructor($$source: Partial<AppendEntryRequestWithDate> = {}) {
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendEntryRequestWithDate instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendEntryRequestWithDate {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new AppendEntryRequestWithDate($$parsedSource as Partial<AppendEntryRequestWithDate>);
    }
}

/**
 * JournalEntry represents a single quick capture entry in a daily journal.
 */
export class JournalEntry {
    "id": string;
    "content": string;
    "tags": string[];
    "created": time$0.Time;
    "deleted"?: boolean;

    /** Creates a new JournalEntry instance. */
    constructor($$source: Partial<JournalEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalEntry {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new JournalEntry($$parsedSource as Partial<JournalEntry>);
    }
}

/**
 * JournalFile represents a daily journal file containing multiple entries.
 */
export class JournalFile {
    "meta": JournalMeta;
    "entries": JournalEntry[];

    /** Creates a new JournalFile instance. */
    constructor($$source: Partial<JournalFile> = {}) {
        if (!("meta" in $$source)) {
            this["meta"] = (new JournalMeta());
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalFile instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalFile {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new JournalFile($$parsedSource as Partial<JournalFile>);
    }
}

/**
 * JournalMeta contains metadata for a daily journal file.
 */
export class JournalMeta {
    "project": string;
    "date": string;
    "created": time$0.Time;
    "updated": time$0.Time;

    /** Creates a new JournalMeta instance. */
    constructor($$source: Partial<JournalMeta> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalMeta($$parsedSource as Partial<JournalMeta>);
    }
}

/**
 * PromoteRequest is the request for promoting entries to a document.
 */
export class PromoteRequest {
    "sourceProject": string;
    "date": string;

    /**
     * empty means whole day
     */
    "entryIds": string[];
    "targetProject": string;
    "title": string;

    /**
     * true = copy, false = move
     */
    "keepOriginal": boolean;

    /** Creates a new PromoteRequest instance. */
    constructor($$source: Partial<PromoteRequest> = {}) {
        if (!("sourceProject" in $$source)) {
            this["sourceProject"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("entryIds" in $$source)) {
            this["entryIds"] = [];
        }
        if (!("targetProject" in $$source)) {
            this["targetProject"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("keepOriginal" in $$source)) {
            this["keepOriginal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromoteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PromoteRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entryIds" in $$parsedSource) {
            $$parsedSource["entryIds"] = $$createField2_0($$parsedSource["entryIds"]);
        }
        return new PromoteRequest($$parsedSource as Partial<PromoteRequest>);
    }
}

/**
 * SearchResult represents a journal entry search result.
 */
export class SearchResult {
    "projectAlias": string;
    "date": string;
    "entry": JournalEntry;
    "snippet": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("entry" in $$source)) {
            this["entry"] = (new JournalEntry());
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField2_0($$parsedSource["entry"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * UpdateEntryRequest is the request for updating an existing entry.
 */
export class UpdateEntryRequest {
    "projectAlias": string;
    "date": string;
    "entryId": string;
    "content": string;

    /**
     * nil means keep existing
     */
    "tags": string[];

    /** Creates a new UpdateEntryRequest instance. */
    constructor($$source: Partial<UpdateEntryRequest> = {}) {
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateEntryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateEntryRequest {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new UpdateEntryRequest($$parsedSource as Partial<UpdateEntryRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = JournalMeta.createFrom;
const $$createType2 = JournalEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
