// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService wraps Service for Wails binding.
 * Methods must be exported and have ctx as first param for Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendEntry adds a quick note to today's journal for the given project.
 * Called from Quick Capture window.
 * @param {$models.AppendEntryRequest} req
 * @returns {$CancellablePromise<$models.JournalEntry | null>}
 */
export function AppendEntry(req) {
    return $Call.ByID(526848289, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppendEntryToDate adds a quick note to a specific date's journal.
 * @param {$models.AppendEntryRequestWithDate} req
 * @returns {$CancellablePromise<$models.JournalEntry | null>}
 */
export function AppendEntryToDate(req) {
    return $Call.ByID(3896369716, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteEntry soft-deletes an entry (sets deleted: true).
 * @param {string} projectAlias
 * @param {string} date
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(projectAlias, date, entryID) {
    return $Call.ByID(680679744, projectAlias, date, entryID);
}

/**
 * GetActiveEntries returns non-deleted entries for a date.
 * @param {string} projectAlias
 * @param {string} date
 * @returns {$CancellablePromise<$models.JournalEntry[]>}
 */
export function GetActiveEntries(projectAlias, date) {
    return $Call.ByID(1550400521, projectAlias, date).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetByDate returns a specific day's journal.
 * @param {string} projectAlias
 * @param {string} date
 * @returns {$CancellablePromise<$models.JournalFile | null>}
 */
export function GetByDate(projectAlias, date) {
    return $Call.ByID(2407524012, projectAlias, date).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetToday returns today's journal for a project.
 * @param {string} projectAlias
 * @returns {$CancellablePromise<$models.JournalFile | null>}
 */
export function GetToday(projectAlias) {
    return $Call.ByID(1029232418, projectAlias).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListDates returns available journal dates for a project.
 * If year and month are both 0, returns all dates.
 * @param {string} projectAlias
 * @param {number} year
 * @param {number} month
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDates(projectAlias, year, month) {
    return $Call.ByID(3792384704, projectAlias, year, month).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * PromoteToDocument converts journal entries to a full document.
 * @param {$models.PromoteRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function PromoteToDocument(req) {
    return $Call.ByID(3459843229, req);
}

/**
 * RestoreEntry restores a soft-deleted entry.
 * @param {string} projectAlias
 * @param {string} date
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreEntry(projectAlias, date, entryID) {
    return $Call.ByID(2191770929, projectAlias, date, entryID);
}

/**
 * SearchEntries searches journal entries across all dates for a project.
 * @param {string} projectAlias
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function SearchEntries(projectAlias, query, limit) {
    return $Call.ByID(411758309, projectAlias, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * UpdateEntry edits an existing entry.
 * @param {$models.UpdateEntryRequest} req
 * @returns {$CancellablePromise<$models.JournalEntry | null>}
 */
export function UpdateEntry(req) {
    return $Call.ByID(2391318982, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.JournalEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.JournalFile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
