// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService wraps Service for Wails binding.
 * Methods must be exported and have ctx as first param for Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendEntry adds a quick note to today's journal for the given project.
 * Called from Quick Capture window.
 */
export function AppendEntry(req: $models.AppendEntryRequest): $CancellablePromise<$models.JournalEntry | null> {
    return $Call.ByID(526848289, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AppendEntryToDate adds a quick note to a specific date's journal.
 */
export function AppendEntryToDate(req: $models.AppendEntryRequestWithDate): $CancellablePromise<$models.JournalEntry | null> {
    return $Call.ByID(3896369716, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteEntry soft-deletes an entry (sets deleted: true).
 */
export function DeleteEntry(projectAlias: string, date: string, entryID: string): $CancellablePromise<void> {
    return $Call.ByID(680679744, projectAlias, date, entryID);
}

/**
 * GetActiveEntries returns non-deleted entries for a date.
 */
export function GetActiveEntries(projectAlias: string, date: string): $CancellablePromise<$models.JournalEntry[]> {
    return $Call.ByID(1550400521, projectAlias, date).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetByDate returns a specific day's journal.
 */
export function GetByDate(projectAlias: string, date: string): $CancellablePromise<$models.JournalFile | null> {
    return $Call.ByID(2407524012, projectAlias, date).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetToday returns today's journal for a project.
 */
export function GetToday(projectAlias: string): $CancellablePromise<$models.JournalFile | null> {
    return $Call.ByID(1029232418, projectAlias).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListDates returns available journal dates for a project.
 * If year and month are both 0, returns all dates.
 */
export function ListDates(projectAlias: string, year: number, month: number): $CancellablePromise<string[]> {
    return $Call.ByID(3792384704, projectAlias, year, month).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PromoteToDocument converts journal entries to a full document.
 */
export function PromoteToDocument(req: $models.PromoteRequest): $CancellablePromise<string> {
    return $Call.ByID(3459843229, req);
}

/**
 * RestoreEntry restores a soft-deleted entry.
 */
export function RestoreEntry(projectAlias: string, date: string, entryID: string): $CancellablePromise<void> {
    return $Call.ByID(2191770929, projectAlias, date, entryID);
}

/**
 * SearchEntries searches journal entries across all dates for a project.
 */
export function SearchEntries(projectAlias: string, query: string, limit: number): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(411758309, projectAlias, query, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * UpdateEntry edits an existing entry.
 */
export function UpdateEntry(req: $models.UpdateEntryRequest): $CancellablePromise<$models.JournalEntry | null> {
    return $Call.ByID(2391318982, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.JournalEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.JournalFile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
