// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';
import {context} from '../models';

export function Get(arg1:string):Promise<document.DocumentWithTags>;

export function HardDelete(arg1:string):Promise<void>;

export function HardDeleteBatch(arg1:Array<string>):Promise<void>;

export function HardDeleteByProject(arg1:string):Promise<void>;

export function ListByProject(arg1:string,arg2:boolean,arg3:number,arg4:number):Promise<Array<document.Document>>;

export function Restore(arg1:string):Promise<void>;

export function Save(arg1:document.SaveRequest):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SoftDelete(arg1:string):Promise<void>;

export function SoftDeleteByProject(arg1:string):Promise<void>;
