// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['document']['Service']['Get'](arg1);
}

export function HardDelete(arg1) {
  return window['go']['document']['Service']['HardDelete'](arg1);
}

export function HardDeleteBatch(arg1) {
  return window['go']['document']['Service']['HardDeleteBatch'](arg1);
}

export function HardDeleteByProject(arg1) {
  return window['go']['document']['Service']['HardDeleteByProject'](arg1);
}

export function ListByProject(arg1, arg2, arg3, arg4) {
  return window['go']['document']['Service']['ListByProject'](arg1, arg2, arg3, arg4);
}

export function Restore(arg1) {
  return window['go']['document']['Service']['Restore'](arg1);
}

export function Save(arg1) {
  return window['go']['document']['Service']['Save'](arg1);
}

export function SetContext(arg1) {
  return window['go']['document']['Service']['SetContext'](arg1);
}

export function SoftDelete(arg1) {
  return window['go']['document']['Service']['SoftDelete'](arg1);
}

export function SoftDeleteByProject(arg1) {
  return window['go']['document']['Service']['SoftDeleteByProject'](arg1);
}
