// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.DocumentCommand[]>}
 */
export function GetAllCommands() {
    return $Call.ByID(2554976200).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} cmd
 * @returns {$CancellablePromise<$models.DocumentResult | null>}
 */
export function Parse(cmd) {
    return $Call.ByID(3666353092, cmd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} cmd
 * @param {string} projectAlias
 * @returns {$CancellablePromise<$models.DocumentResult | null>}
 */
export function ParseWithContext(cmd, projectAlias) {
    return $Call.ByID(3002238175, cmd, projectAlias).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} cmd
 * @param {string} docPath
 * @returns {$CancellablePromise<$models.DocumentResult | null>}
 */
export function ParseWithDocument(cmd, docPath) {
    return $Call.ByID(2114957901, cmd, docPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentDocument(path) {
    return $Call.ByID(1582368453, path);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.DocumentResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
