// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllCommands(): $CancellablePromise<$models.DocumentCommand[]> {
    return $Call.ByID(2554976200).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Parse(cmd: string): $CancellablePromise<$models.DocumentResult | null> {
    return $Call.ByID(3666353092, cmd).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ParseWithContext(cmd: string, projectAlias: string): $CancellablePromise<$models.DocumentResult | null> {
    return $Call.ByID(3002238175, cmd, projectAlias).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ParseWithDocument(cmd: string, docPath: string): $CancellablePromise<$models.DocumentResult | null> {
    return $Call.ByID(2114957901, cmd, docPath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetCurrentDocument(path: string): $CancellablePromise<void> {
    return $Call.ByID(1582368453, path);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.DocumentResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
