// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllCommands(): $CancellablePromise<$models.GlobalCommand[]> {
    return $Call.ByID(2651950074).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProjectCache(): $CancellablePromise<project$0.Cache | null> {
    return $Call.ByID(3139646428).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Parse(cmd: string): $CancellablePromise<$models.GlobalResult | null> {
    return $Call.ByID(1678741870, cmd).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = project$0.Cache.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.GlobalResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
