// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

export enum CommandContext {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextProject = "project",
    ContextEntry = "entry",
    ContextTag = "tag",
    ContextSearch = "search",
    ContextSystem = "system",
    ContextGlobal = "global",
};

export enum DocumentCommand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DocumentCommandNew = "new",
    DocumentCommandDoc = "doc",
    DocumentCommandArchive = "archive",
    DocumentCommandUnarchive = "unarchive",
    DocumentCommandDelete = "delete",
    DocumentCommandTag = "tag",
    DocumentCommandUntag = "untag",
    DocumentCommandTags = "tags",
};

export class DocumentResult {
    "success": boolean;
    "message": string;
    "data"?: DocumentResultData;
    "context": CommandContext;

    /** Creates a new DocumentResult instance. */
    constructor($$source: Partial<DocumentResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new DocumentResult($$parsedSource as Partial<DocumentResult>);
    }
}

export class DocumentResultData {
    "documentPath"?: string;
    "title"?: string;
    "flags"?: string[];
    "requiresConfirmation"?: boolean;
    "confirmationCommand"?: string;

    /** Creates a new DocumentResultData instance. */
    constructor($$source: Partial<DocumentResultData> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResultData instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentResultData {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField2_0($$parsedSource["flags"]);
        }
        return new DocumentResultData($$parsedSource as Partial<DocumentResultData>);
    }
}

export enum GlobalCommand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GlobalCommandSwitch = "switch",
    GlobalCommandSync = "sync",
    GlobalCommandQuit = "quit",
};

export class GlobalResult {
    "success": boolean;
    "message": string;
    "data"?: GlobalResultData;
    "context": CommandContext;

    /** Creates a new GlobalResult instance. */
    constructor($$source: Partial<GlobalResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new GlobalResult($$parsedSource as Partial<GlobalResult>);
    }
}

export class GlobalResultData {
    "project"?: project$0.Project | null;

    /** Creates a new GlobalResultData instance. */
    constructor($$source: Partial<GlobalResultData> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalResultData instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalResultData {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        return new GlobalResultData($$parsedSource as Partial<GlobalResultData>);
    }
}

export enum ProjectCommand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProjectCommandNew = "new",
    ProjectCommandArchive = "archive",
    ProjectCommandUnarchive = "unarchive",
    ProjectCommandRename = "rename",
    ProjectCommandDelete = "delete",
};

export class ProjectResult {
    "success": boolean;
    "message": string;
    "data"?: ProjectResultData;
    "context": CommandContext;

    /** Creates a new ProjectResult instance. */
    constructor($$source: Partial<ProjectResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectResult {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ProjectResult($$parsedSource as Partial<ProjectResult>);
    }
}

export class ProjectResultData {
    "project"?: project$0.Project | null;
    "alias"?: string;
    "flags"?: string[];
    "requiresConfirmation"?: boolean;
    "confirmationCommand"?: string;

    /** Creates a new ProjectResultData instance. */
    constructor($$source: Partial<ProjectResultData> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResultData instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectResultData {
        const $$createField0_0 = $$createType4;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField2_0($$parsedSource["flags"]);
        }
        return new ProjectResultData($$parsedSource as Partial<ProjectResultData>);
    }
}

// Private type creation functions
const $$createType0 = DocumentResultData.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = GlobalResultData.createFrom;
const $$createType3 = project$0.Project.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ProjectResultData.createFrom;
