// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * @readonly
 * @enum {string}
 */
export const CommandContext = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ContextProject: "project",
    ContextEntry: "entry",
    ContextTag: "tag",
    ContextSearch: "search",
    ContextSystem: "system",
    ContextGlobal: "global",
};

/**
 * @readonly
 * @enum {string}
 */
export const DocumentCommand = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DocumentCommandNew: "new",
    DocumentCommandDoc: "doc",
    DocumentCommandArchive: "archive",
    DocumentCommandUnarchive: "unarchive",
    DocumentCommandDelete: "delete",
    DocumentCommandTag: "tag",
    DocumentCommandUntag: "untag",
    DocumentCommandTags: "tags",
    DocumentCommandExport: "export",
};

export class DocumentResult {
    /**
     * Creates a new DocumentResult instance.
     * @param {Partial<DocumentResult>} [$$source = {}] - The source object to create the DocumentResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DocumentResultData | undefined}
             */
            this["data"] = undefined;
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {CommandContext}
             */
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new DocumentResult(/** @type {Partial<DocumentResult>} */($$parsedSource));
    }
}

export class DocumentResultData {
    /**
     * Creates a new DocumentResultData instance.
     * @param {Partial<DocumentResultData>} [$$source = {}] - The source object to create the DocumentResultData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["documentPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["flags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["confirmationCommand"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResultData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentResultData}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField2_0($$parsedSource["flags"]);
        }
        return new DocumentResultData(/** @type {Partial<DocumentResultData>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const GlobalCommand = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    GlobalCommandSwitch: "switch",
    GlobalCommandSync: "sync",
    GlobalCommandQuit: "quit",
};

export class GlobalResult {
    /**
     * Creates a new GlobalResult instance.
     * @param {Partial<GlobalResult>} [$$source = {}] - The source object to create the GlobalResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GlobalResultData | undefined}
             */
            this["data"] = undefined;
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {CommandContext}
             */
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new GlobalResult(/** @type {Partial<GlobalResult>} */($$parsedSource));
    }
}

export class GlobalResultData {
    /**
     * Creates a new GlobalResultData instance.
     * @param {Partial<GlobalResultData>} [$$source = {}] - The source object to create the GlobalResultData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {project$0.Project | null | undefined}
             */
            this["project"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalResultData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalResultData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        return new GlobalResultData(/** @type {Partial<GlobalResultData>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ProjectCommand = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProjectCommandNew: "new",
    ProjectCommandArchive: "archive",
    ProjectCommandUnarchive: "unarchive",
    ProjectCommandRename: "rename",
    ProjectCommandDelete: "delete",
};

export class ProjectResult {
    /**
     * Creates a new ProjectResult instance.
     * @param {Partial<ProjectResult>} [$$source = {}] - The source object to create the ProjectResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProjectResultData | undefined}
             */
            this["data"] = undefined;
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {CommandContext}
             */
            this["context"] = CommandContext.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ProjectResult(/** @type {Partial<ProjectResult>} */($$parsedSource));
    }
}

export class ProjectResultData {
    /**
     * Creates a new ProjectResultData instance.
     * @param {Partial<ProjectResultData>} [$$source = {}] - The source object to create the ProjectResultData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {project$0.Project | null | undefined}
             */
            this["project"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["alias"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["flags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["confirmationCommand"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResultData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectResultData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField2_0($$parsedSource["flags"]);
        }
        return new ProjectResultData(/** @type {Partial<ProjectResultData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DocumentResultData.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = GlobalResultData.createFrom;
const $$createType3 = project$0.Project.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ProjectResultData.createFrom;
