// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllCommands(): $CancellablePromise<$models.ProjectCommand[]> {
    return $Call.ByID(887704796).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Parse(cmd: string): $CancellablePromise<$models.ProjectResult | null> {
    return $Call.ByID(2407191848, cmd).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.ProjectResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
