// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} docPath
 * @param {string[]} tagNames
 * @returns {$CancellablePromise<void>}
 */
export function AddTagsToDocument(docPath, tagNames) {
    return $Call.ByID(1902337286, docPath, tagNames);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Create(name) {
    return $Call.ByID(1870183916, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Delete(name) {
    return $Call.ByID(1760924499, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.Tag | null>}
 */
export function GetByName(name) {
    return $Call.ByID(3962019770, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} docPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDocumentTags(docPath) {
    return $Call.ByID(1181694480, docPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.Tag | null)[]>}
 */
export function ListActive() {
    return $Call.ByID(1660515450).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} docPath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAllDocumentTags(docPath) {
    return $Call.ByID(541033231, docPath);
}

/**
 * @param {string} docPath
 * @param {string[]} tagNames
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTagsFromDocument(docPath, tagNames) {
    return $Call.ByID(2823586728, docPath, tagNames);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Restore(name) {
    return $Call.ByID(1000940746, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SoftDelete(name) {
    return $Call.ByID(192425771, name);
}

// Private type creation functions
const $$createType0 = $models.Tag.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType1);
