// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTagsToDocument(docPath: string, tagNames: string[]): $CancellablePromise<void> {
    return $Call.ByID(1902337286, docPath, tagNames);
}

export function Create(name: string): $CancellablePromise<string> {
    return $Call.ByID(1870183916, name);
}

export function Delete(name: string): $CancellablePromise<void> {
    return $Call.ByID(1760924499, name);
}

export function GetByName(name: string): $CancellablePromise<$models.Tag | null> {
    return $Call.ByID(3962019770, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDocumentTags(docPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(1181694480, docPath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListActive(): $CancellablePromise<($models.Tag | null)[]> {
    return $Call.ByID(1660515450).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveAllDocumentTags(docPath: string): $CancellablePromise<void> {
    return $Call.ByID(541033231, docPath);
}

export function RemoveTagsFromDocument(docPath: string, tagNames: string[]): $CancellablePromise<void> {
    return $Call.ByID(2823586728, docPath, tagNames);
}

export function Restore(name: string): $CancellablePromise<void> {
    return $Call.ByID(1000940746, name);
}

export function SoftDelete(name: string): $CancellablePromise<void> {
    return $Call.ByID(192425771, name);
}

// Private type creation functions
const $$createType0 = $models.Tag.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType1);
