// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildURL(arg1, arg2, arg3) {
  return window['go']['asset']['Service']['BuildURL'](arg1, arg2, arg3);
}

export function CleanupOrphans(arg1) {
  return window['go']['asset']['Service']['CleanupOrphans'](arg1);
}

export function LinkToDocument(arg1, arg2) {
  return window['go']['asset']['Service']['LinkToDocument'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['asset']['Service']['SetContext'](arg1);
}

export function UnlinkAllFromDocument(arg1) {
  return window['go']['asset']['Service']['UnlinkAllFromDocument'](arg1);
}

export function UnlinkFromDocument(arg1, arg2) {
  return window['go']['asset']['Service']['UnlinkFromDocument'](arg1, arg2);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['asset']['Service']['Upload'](arg1, arg2, arg3);
}
