// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {asset} from '../models';

export function BuildURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CleanupOrphans(arg1:string):Promise<number>;

export function LinkToDocument(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UnlinkAllFromDocument(arg1:string):Promise<void>;

export function UnlinkFromDocument(arg1:string,arg2:string):Promise<void>;

export function Upload(arg1:string,arg2:Array<number>,arg3:string):Promise<asset.AssetInfo>;
