// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as events$0 from "../../../../../yanta/internal/events/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "yanta/entry/created": events$0.EntryCreatedData;
            "yanta/entry/updated": events$0.EntryUpdatedData;
            "yanta/project/changed": events$0.ProjectChangedData;
        }
    }
}
