//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../../../../../yanta/internal/events/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "yanta/entry/created": $$createType0,
        "yanta/entry/updated": $$createType1,
        "yanta/project/changed": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = events$0.EntryCreatedData.createFrom;
const $$createType1 = events$0.EntryUpdatedData.createFrom;
const $$createType2 = events$0.ProjectChangedData.createFrom;

configure();
