# Generated by Yanta release pipeline
pkgname = yanta
pkgbase = yanta
pkgver = @PKGVER@
pkgdesc = Yet Another Note Taking App
url = https://github.com/mrgeek/yanta
builddate = @BUILDDATE@
packager = Yanta Release Pipeline
size = @SIZE@
arch = x86_64
license = MIT
depend = gtk3
depend = webkit2gtk-4.1
depend = glib2
provides = yanta
