// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Query(arg1, arg2, arg3) {
  return window['go']['search']['Service']['Query'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['search']['Service']['SetContext'](arg1);
}
