// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';
import {context} from '../models';

export function Query(arg1:string,arg2:number,arg3:number):Promise<Array<search.Result>>;

export function SetContext(arg1:context.Context):Promise<void>;
