// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ExportRequest {
    "DocumentPath": string;
    "OutputPath": string;

    /** Creates a new ExportRequest instance. */
    constructor($$source: Partial<ExportRequest> = {}) {
        if (!("DocumentPath" in $$source)) {
            this["DocumentPath"] = "";
        }
        if (!("OutputPath" in $$source)) {
            this["OutputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRequest($$parsedSource as Partial<ExportRequest>);
    }
}
