// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ExportRequest {
    /**
     * Creates a new ExportRequest instance.
     * @param {Partial<ExportRequest>} [$$source = {}] - The source object to create the ExportRequest.
     */
    constructor($$source = {}) {
        if (!("DocumentPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DocumentPath"] = "";
        }
        if (!("OutputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["OutputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRequest(/** @type {Partial<ExportRequest>} */($$parsedSource));
    }
}
