// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntryCreatedData is the payload for entry creation events.
 * Fields are optional (pointers) because documents and journal entries
 * emit different subsets: documents use Path/Title, journals use Date/EntryID.
 */
export class EntryCreatedData {
    /**
     * Creates a new EntryCreatedData instance.
     * @param {Partial<EntryCreatedData>} [$$source = {}] - The source object to create the EntryCreatedData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "journal" or "document"
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * journal entries only
             * @member
             * @type {string | undefined}
             */
            this["date"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * journal entries only
             * @member
             * @type {string | undefined}
             */
            this["entryId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryCreatedData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryCreatedData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryCreatedData(/** @type {Partial<EntryCreatedData>} */($$parsedSource));
    }
}

/**
 * EntryUpdatedData is the payload for entry update events.
 */
export class EntryUpdatedData {
    /**
     * Creates a new EntryUpdatedData instance.
     * @param {Partial<EntryUpdatedData>} [$$source = {}] - The source object to create the EntryUpdatedData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["date"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["entryId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryUpdatedData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryUpdatedData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryUpdatedData(/** @type {Partial<EntryUpdatedData>} */($$parsedSource));
    }
}

/**
 * ProjectChangedData is the payload for project lifecycle events.
 */
export class ProjectChangedData {
    /**
     * Creates a new ProjectChangedData instance.
     * @param {Partial<ProjectChangedData>} [$$source = {}] - The source object to create the ProjectChangedData.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("op" in $$source)) {
            /**
             * "create", "update", "delete", "restore"
             * @member
             * @type {string}
             */
            this["op"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectChangedData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectChangedData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectChangedData(/** @type {Partial<ProjectChangedData>} */($$parsedSource));
    }
}
