// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Indexer {

    /** Creates a new Indexer instance. */
    constructor($$source: Partial<Indexer> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Indexer instance from a string or object.
     */
    static createFrom($$source: any = {}): Indexer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Indexer($$parsedSource as Partial<Indexer>);
    }
}
