// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MigrationConflictInfo contains conflict detection results for a migration.
 */
export class MigrationConflictInfo {
    "hasConflict": boolean;
    "localVault"?: VaultStats | null;
    "targetVault"?: VaultStats | null;
    "localPath": string;
    "targetPath": string;

    /** Creates a new MigrationConflictInfo instance. */
    constructor($$source: Partial<MigrationConflictInfo> = {}) {
        if (!("hasConflict" in $$source)) {
            this["hasConflict"] = false;
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationConflictInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationConflictInfo {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localVault" in $$parsedSource) {
            $$parsedSource["localVault"] = $$createField1_0($$parsedSource["localVault"]);
        }
        if ("targetVault" in $$parsedSource) {
            $$parsedSource["targetVault"] = $$createField2_0($$parsedSource["targetVault"]);
        }
        return new MigrationConflictInfo($$parsedSource as Partial<MigrationConflictInfo>);
    }
}

/**
 * MigrationStrategy represents how to resolve conflicts when both local and target have vault data.
 */
export enum MigrationStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StrategyUseRemote keeps the target vault and discards local data (current behavior).
     */
    StrategyUseRemote = "use_remote",

    /**
     * StrategyUseLocal copies local vault to target, overwriting target data (backs up target first).
     */
    StrategyUseLocal = "use_local",

    /**
     * StrategyMergeBoth copies local files that don't exist in target, preserving target's existing files.
     */
    StrategyMergeBoth = "merge_both",
};

/**
 * VaultStats contains statistics about a vault directory.
 */
export class VaultStats {
    "documentCount": number;
    "projectCount": number;
    "totalSize": number;
    "totalSizeHuman": string;

    /** Creates a new VaultStats instance. */
    constructor($$source: Partial<VaultStats> = {}) {
        if (!("documentCount" in $$source)) {
            this["documentCount"] = 0;
        }
        if (!("projectCount" in $$source)) {
            this["projectCount"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("totalSizeHuman" in $$source)) {
            this["totalSizeHuman"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStats instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStats($$parsedSource as Partial<VaultStats>);
    }
}

// Private type creation functions
const $$createType0 = VaultStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
