// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MigrationConflictInfo contains conflict detection results for a migration.
 */
export class MigrationConflictInfo {
    /**
     * Creates a new MigrationConflictInfo instance.
     * @param {Partial<MigrationConflictInfo>} [$$source = {}] - The source object to create the MigrationConflictInfo.
     */
    constructor($$source = {}) {
        if (!("hasConflict" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasConflict"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VaultStats | null | undefined}
             */
            this["localVault"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VaultStats | null | undefined}
             */
            this["targetVault"] = undefined;
        }
        if (!("localPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationConflictInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrationConflictInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localVault" in $$parsedSource) {
            $$parsedSource["localVault"] = $$createField1_0($$parsedSource["localVault"]);
        }
        if ("targetVault" in $$parsedSource) {
            $$parsedSource["targetVault"] = $$createField2_0($$parsedSource["targetVault"]);
        }
        return new MigrationConflictInfo(/** @type {Partial<MigrationConflictInfo>} */($$parsedSource));
    }
}

/**
 * MigrationStrategy represents how to resolve conflicts when both local and target have vault data.
 * @readonly
 * @enum {string}
 */
export const MigrationStrategy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StrategyUseRemote keeps the target vault and discards local data (current behavior).
     */
    StrategyUseRemote: "use_remote",

    /**
     * StrategyUseLocal copies local vault to target, overwriting target data (backs up target first).
     */
    StrategyUseLocal: "use_local",

    /**
     * StrategyMergeBoth copies local files that don't exist in target, preserving target's existing files.
     */
    StrategyMergeBoth: "merge_both",
};

/**
 * VaultStats contains statistics about a vault directory.
 */
export class VaultStats {
    /**
     * Creates a new VaultStats instance.
     * @param {Partial<VaultStats>} [$$source = {}] - The source object to create the VaultStats.
     */
    constructor($$source = {}) {
        if (!("documentCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["documentCount"] = 0;
        }
        if (!("projectCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectCount"] = 0;
        }
        if (!("totalSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSize"] = 0;
        }
        if (!("totalSizeHuman" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalSizeHuman"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStats(/** @type {Partial<VaultStats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VaultStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
