// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Cache {
    /**
     * Creates a new Cache instance.
     * @param {Partial<Cache>} [$$source = {}] - The source object to create the Cache.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cache instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cache}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cache(/** @type {Partial<Cache>} */($$parsedSource));
    }
}

export class Project {
    /**
     * Creates a new Project instance.
     * @param {Partial<Project>} [$$source = {}] - The source object to create the Project.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("start_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["end_date"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deleted_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Project}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project(/** @type {Partial<Project>} */($$parsedSource));
    }
}
