// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(name: string, alias: string, startDate: string, endDate: string): $CancellablePromise<string> {
    return $Call.ByID(323823275, name, alias, startDate, endDate);
}

/**
 * If project has documents: soft delete project (documents handled separately)
 * If no documents: hard delete project
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2740200680, id);
}

export function Get(id: string): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(140703701, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAllDocumentCounts(): $CancellablePromise<{ [_: string]: number }> {
    return $Call.ByID(251687541).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAllLastDocumentDates(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(803814606).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCache(): $CancellablePromise<$models.Cache | null> {
    return $Call.ByID(2398912437).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDocumentCount(projectID: string): $CancellablePromise<number> {
    return $Call.ByID(3891848187, projectID);
}

export function HardDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3536514201, id);
}

export function ListActive(): $CancellablePromise<($models.Project | null)[]> {
    return $Call.ByID(4034040781).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListArchived(): $CancellablePromise<($models.Project | null)[]> {
    return $Call.ByID(265614285).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Restore(id: string): $CancellablePromise<void> {
    return $Call.ByID(1142820843, id);
}

export function SoftDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1921200564, id);
}

export function Update(p: $models.Project | null): $CancellablePromise<void> {
    return $Call.ByID(2639904378, p);
}

export function UpdateDocumentCount(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(354900446, projectID);
}

// Private type creation functions
const $$createType0 = $models.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.Cache.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType1);
