// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} alias
 * @param {string} startDate
 * @param {string} endDate
 * @returns {$CancellablePromise<string>}
 */
export function Create(name, alias, startDate, endDate) {
    return $Call.ByID(323823275, name, alias, startDate, endDate);
}

/**
 * If project has documents: soft delete project (documents handled separately)
 * If no documents: hard delete project
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2740200680, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Project | null>}
 */
export function Get(id) {
    return $Call.ByID(140703701, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: number }>}
 */
export function GetAllDocumentCounts() {
    return $Call.ByID(251687541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAllLastDocumentDates() {
    return $Call.ByID(803814606).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Cache | null>}
 */
export function GetCache() {
    return $Call.ByID(2398912437).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<number>}
 */
export function GetDocumentCount(projectID) {
    return $Call.ByID(3891848187, projectID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function HardDelete(id) {
    return $Call.ByID(3536514201, id);
}

/**
 * @returns {$CancellablePromise<($models.Project | null)[]>}
 */
export function ListActive() {
    return $Call.ByID(4034040781).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.Project | null)[]>}
 */
export function ListArchived() {
    return $Call.ByID(265614285).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Restore(id) {
    return $Call.ByID(1142820843, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SoftDelete(id) {
    return $Call.ByID(1921200564, id);
}

/**
 * @param {$models.Project | null} p
 * @returns {$CancellablePromise<void>}
 */
export function Update(p) {
    return $Call.ByID(2639904378, p);
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDocumentCount(projectID) {
    return $Call.ByID(354900446, projectID);
}

// Private type creation functions
const $$createType0 = $models.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.Cache.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType1);
