// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssetInfo {
    "Hash": string;
    "Ext": string;
    "Bytes": number;
    "MIME": string;
    "AlreadyExist": boolean;

    /** Creates a new AssetInfo instance. */
    constructor($$source: Partial<AssetInfo> = {}) {
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Ext" in $$source)) {
            this["Ext"] = "";
        }
        if (!("Bytes" in $$source)) {
            this["Bytes"] = 0;
        }
        if (!("MIME" in $$source)) {
            this["MIME"] = "";
        }
        if (!("AlreadyExist" in $$source)) {
            this["AlreadyExist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetInfo($$parsedSource as Partial<AssetInfo>);
    }
}

export class FinalizeChunkedUploadResponse {
    "url": string;
    "hash": string;
    "ext": string;
    "bytes": number;

    /** Creates a new FinalizeChunkedUploadResponse instance. */
    constructor($$source: Partial<FinalizeChunkedUploadResponse> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FinalizeChunkedUploadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): FinalizeChunkedUploadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FinalizeChunkedUploadResponse($$parsedSource as Partial<FinalizeChunkedUploadResponse>);
    }
}

export class StartChunkedUploadRequest {
    "projectAlias": string;
    "filename": string;
    "totalSize": number;
    "totalChunks": number;
    "mimeType": string;

    /** Creates a new StartChunkedUploadRequest instance. */
    constructor($$source: Partial<StartChunkedUploadRequest> = {}) {
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("totalChunks" in $$source)) {
            this["totalChunks"] = 0;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartChunkedUploadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartChunkedUploadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartChunkedUploadRequest($$parsedSource as Partial<StartChunkedUploadRequest>);
    }
}

export class StartChunkedUploadResponse {
    "uploadId": string;

    /** Creates a new StartChunkedUploadResponse instance. */
    constructor($$source: Partial<StartChunkedUploadResponse> = {}) {
        if (!("uploadId" in $$source)) {
            this["uploadId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartChunkedUploadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): StartChunkedUploadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartChunkedUploadResponse($$parsedSource as Partial<StartChunkedUploadResponse>);
    }
}

export class UploadChunkRequest {
    "uploadId": string;
    "chunkIndex": number;
    "data": string;

    /** Creates a new UploadChunkRequest instance. */
    constructor($$source: Partial<UploadChunkRequest> = {}) {
        if (!("uploadId" in $$source)) {
            this["uploadId"] = "";
        }
        if (!("chunkIndex" in $$source)) {
            this["chunkIndex"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadChunkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadChunkRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadChunkRequest($$parsedSource as Partial<UploadChunkRequest>);
    }
}

export class UploadChunkResponse {
    "receivedChunks": number;
    "complete": boolean;

    /** Creates a new UploadChunkResponse instance. */
    constructor($$source: Partial<UploadChunkResponse> = {}) {
        if (!("receivedChunks" in $$source)) {
            this["receivedChunks"] = 0;
        }
        if (!("complete" in $$source)) {
            this["complete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadChunkResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadChunkResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadChunkResponse($$parsedSource as Partial<UploadChunkResponse>);
    }
}
