// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssetInfo {
    /**
     * Creates a new AssetInfo instance.
     * @param {Partial<AssetInfo>} [$$source = {}] - The source object to create the AssetInfo.
     */
    constructor($$source = {}) {
        if (!("Hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Hash"] = "";
        }
        if (!("Ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ext"] = "";
        }
        if (!("Bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Bytes"] = 0;
        }
        if (!("MIME" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MIME"] = "";
        }
        if (!("AlreadyExist" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AlreadyExist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetInfo(/** @type {Partial<AssetInfo>} */($$parsedSource));
    }
}

export class FinalizeChunkedUploadResponse {
    /**
     * Creates a new FinalizeChunkedUploadResponse instance.
     * @param {Partial<FinalizeChunkedUploadResponse>} [$$source = {}] - The source object to create the FinalizeChunkedUploadResponse.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FinalizeChunkedUploadResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FinalizeChunkedUploadResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FinalizeChunkedUploadResponse(/** @type {Partial<FinalizeChunkedUploadResponse>} */($$parsedSource));
    }
}

export class StartChunkedUploadRequest {
    /**
     * Creates a new StartChunkedUploadRequest instance.
     * @param {Partial<StartChunkedUploadRequest>} [$$source = {}] - The source object to create the StartChunkedUploadRequest.
     */
    constructor($$source = {}) {
        if (!("projectAlias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("totalSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSize"] = 0;
        }
        if (!("totalChunks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalChunks"] = 0;
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartChunkedUploadRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartChunkedUploadRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartChunkedUploadRequest(/** @type {Partial<StartChunkedUploadRequest>} */($$parsedSource));
    }
}

export class StartChunkedUploadResponse {
    /**
     * Creates a new StartChunkedUploadResponse instance.
     * @param {Partial<StartChunkedUploadResponse>} [$$source = {}] - The source object to create the StartChunkedUploadResponse.
     */
    constructor($$source = {}) {
        if (!("uploadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploadId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartChunkedUploadResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartChunkedUploadResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartChunkedUploadResponse(/** @type {Partial<StartChunkedUploadResponse>} */($$parsedSource));
    }
}

export class UploadChunkRequest {
    /**
     * Creates a new UploadChunkRequest instance.
     * @param {Partial<UploadChunkRequest>} [$$source = {}] - The source object to create the UploadChunkRequest.
     */
    constructor($$source = {}) {
        if (!("uploadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploadId"] = "";
        }
        if (!("chunkIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunkIndex"] = 0;
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadChunkRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UploadChunkRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadChunkRequest(/** @type {Partial<UploadChunkRequest>} */($$parsedSource));
    }
}

export class UploadChunkResponse {
    /**
     * Creates a new UploadChunkResponse instance.
     * @param {Partial<UploadChunkResponse>} [$$source = {}] - The source object to create the UploadChunkResponse.
     */
    constructor($$source = {}) {
        if (!("receivedChunks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["receivedChunks"] = 0;
        }
        if (!("complete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["complete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadChunkResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UploadChunkResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadChunkResponse(/** @type {Partial<UploadChunkResponse>} */($$parsedSource));
    }
}
