// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AbortChunkedUpload(uploadID: string): $CancellablePromise<void> {
    return $Call.ByID(3467454059, uploadID);
}

export function BuildURL(projectAlias: string, hash: string, ext: string): $CancellablePromise<string> {
    return $Call.ByID(2109959169, projectAlias, hash, ext);
}

export function CleanupOrphans(projectAlias: string): $CancellablePromise<number> {
    return $Call.ByID(918347355, projectAlias);
}

export function FinalizeChunkedUpload(uploadID: string): $CancellablePromise<$models.FinalizeChunkedUploadResponse | null> {
    return $Call.ByID(1744410067, uploadID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LinkToDocument(docPath: string, hash: string): $CancellablePromise<void> {
    return $Call.ByID(193878512, docPath, hash);
}

export function StartChunkedUpload(req: $models.StartChunkedUploadRequest): $CancellablePromise<$models.StartChunkedUploadResponse | null> {
    return $Call.ByID(1430739033, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UnlinkAllFromDocument(docPath: string): $CancellablePromise<void> {
    return $Call.ByID(854899483, docPath);
}

export function UnlinkFromDocument(docPath: string, hash: string): $CancellablePromise<void> {
    return $Call.ByID(1214500222, docPath, hash);
}

export function Upload(projectAlias: string, data: string, filename: string): $CancellablePromise<$models.AssetInfo | null> {
    return $Call.ByID(3335014721, projectAlias, data, filename).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UploadChunk(req: $models.UploadChunkRequest): $CancellablePromise<$models.UploadChunkResponse | null> {
    return $Call.ByID(3545445334, req).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FinalizeChunkedUploadResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.StartChunkedUploadResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AssetInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.UploadChunkResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
