// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} uploadID
 * @returns {$CancellablePromise<void>}
 */
export function AbortChunkedUpload(uploadID) {
    return $Call.ByID(3467454059, uploadID);
}

/**
 * @param {string} projectAlias
 * @param {string} hash
 * @param {string} ext
 * @returns {$CancellablePromise<string>}
 */
export function BuildURL(projectAlias, hash, ext) {
    return $Call.ByID(2109959169, projectAlias, hash, ext);
}

/**
 * @param {string} projectAlias
 * @returns {$CancellablePromise<number>}
 */
export function CleanupOrphans(projectAlias) {
    return $Call.ByID(918347355, projectAlias);
}

/**
 * @param {string} uploadID
 * @returns {$CancellablePromise<$models.FinalizeChunkedUploadResponse | null>}
 */
export function FinalizeChunkedUpload(uploadID) {
    return $Call.ByID(1744410067, uploadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} docPath
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function LinkToDocument(docPath, hash) {
    return $Call.ByID(193878512, docPath, hash);
}

/**
 * @param {$models.StartChunkedUploadRequest} req
 * @returns {$CancellablePromise<$models.StartChunkedUploadResponse | null>}
 */
export function StartChunkedUpload(req) {
    return $Call.ByID(1430739033, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} docPath
 * @returns {$CancellablePromise<void>}
 */
export function UnlinkAllFromDocument(docPath) {
    return $Call.ByID(854899483, docPath);
}

/**
 * @param {string} docPath
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function UnlinkFromDocument(docPath, hash) {
    return $Call.ByID(1214500222, docPath, hash);
}

/**
 * @param {string} projectAlias
 * @param {string} data
 * @param {string} filename
 * @returns {$CancellablePromise<$models.AssetInfo | null>}
 */
export function Upload(projectAlias, data, filename) {
    return $Call.ByID(3335014721, projectAlias, data, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.UploadChunkRequest} req
 * @returns {$CancellablePromise<$models.UploadChunkResponse | null>}
 */
export function UploadChunk(req) {
    return $Call.ByID(3545445334, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.FinalizeChunkedUploadResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.StartChunkedUploadResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AssetInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.UploadChunkResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
