// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['project']['Service']['Create'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1) {
  return window['go']['project']['Service']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['project']['Service']['Get'](arg1);
}

export function GetAllDocumentCounts() {
  return window['go']['project']['Service']['GetAllDocumentCounts']();
}

export function GetAllLastDocumentDates() {
  return window['go']['project']['Service']['GetAllLastDocumentDates']();
}

export function GetCache() {
  return window['go']['project']['Service']['GetCache']();
}

export function GetDocumentCount(arg1) {
  return window['go']['project']['Service']['GetDocumentCount'](arg1);
}

export function HardDelete(arg1) {
  return window['go']['project']['Service']['HardDelete'](arg1);
}

export function ListActive() {
  return window['go']['project']['Service']['ListActive']();
}

export function ListArchived() {
  return window['go']['project']['Service']['ListArchived']();
}

export function Restore(arg1) {
  return window['go']['project']['Service']['Restore'](arg1);
}

export function SetContext(arg1) {
  return window['go']['project']['Service']['SetContext'](arg1);
}

export function SoftDelete(arg1) {
  return window['go']['project']['Service']['SoftDelete'](arg1);
}

export function Update(arg1) {
  return window['go']['project']['Service']['Update'](arg1);
}

export function UpdateDocumentCount(arg1) {
  return window['go']['project']['Service']['UpdateDocumentCount'](arg1);
}
