// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<project.Project>;

export function GetAllDocumentCounts():Promise<Record<string, number>>;

export function GetAllLastDocumentDates():Promise<Record<string, string>>;

export function GetCache():Promise<project.Cache>;

export function GetDocumentCount(arg1:string):Promise<number>;

export function HardDelete(arg1:string):Promise<void>;

export function ListActive():Promise<Array<project.Project>>;

export function ListArchived():Promise<Array<project.Project>>;

export function Restore(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SoftDelete(arg1:string):Promise<void>;

export function Update(arg1:project.Project):Promise<void>;

export function UpdateDocumentCount(arg1:string):Promise<void>;
