// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tag} from '../models';
import {context} from '../models';

export function AddTagsToDocument(arg1:string,arg2:Array<string>):Promise<void>;

export function Create(arg1:string):Promise<string>;

export function Delete(arg1:string):Promise<void>;

export function GetByName(arg1:string):Promise<tag.Tag>;

export function GetDocumentTags(arg1:string):Promise<Array<string>>;

export function ListActive():Promise<Array<tag.Tag>>;

export function RemoveAllDocumentTags(arg1:string):Promise<void>;

export function RemoveTagsFromDocument(arg1:string,arg2:Array<string>):Promise<void>;

export function Restore(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SoftDelete(arg1:string):Promise<void>;
