// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagsToDocument(arg1, arg2) {
  return window['go']['tag']['Service']['AddTagsToDocument'](arg1, arg2);
}

export function Create(arg1) {
  return window['go']['tag']['Service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['tag']['Service']['Delete'](arg1);
}

export function GetByName(arg1) {
  return window['go']['tag']['Service']['GetByName'](arg1);
}

export function GetDocumentTags(arg1) {
  return window['go']['tag']['Service']['GetDocumentTags'](arg1);
}

export function ListActive() {
  return window['go']['tag']['Service']['ListActive']();
}

export function RemoveAllDocumentTags(arg1) {
  return window['go']['tag']['Service']['RemoveAllDocumentTags'](arg1);
}

export function RemoveTagsFromDocument(arg1, arg2) {
  return window['go']['tag']['Service']['RemoveTagsFromDocument'](arg1, arg2);
}

export function Restore(arg1) {
  return window['go']['tag']['Service']['Restore'](arg1);
}

export function SetContext(arg1) {
  return window['go']['tag']['Service']['SetContext'](arg1);
}

export function SoftDelete(arg1) {
  return window['go']['tag']['Service']['SoftDelete'](arg1);
}
