// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackupConfig {
    /**
     * Creates a new BackupConfig instance.
     * @param {Partial<BackupConfig>} [$$source = {}] - The source object to create the BackupConfig.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("MaxBackups" in $$source)) {
            /**
             * number of backups to retain, 0 = unlimited
             * @member
             * @type {number}
             */
            this["MaxBackups"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupConfig(/** @type {Partial<BackupConfig>} */($$parsedSource));
    }
}

export class GitSyncConfig {
    /**
     * Creates a new GitSyncConfig instance.
     * @param {Partial<GitSyncConfig>} [$$source = {}] - The source object to create the GitSyncConfig.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("AutoCommit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoCommit"] = false;
        }
        if (!("AutoPush" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoPush"] = false;
        }
        if (!("CommitInterval" in $$source)) {
            /**
             * minutes between auto-commits, 0 = manual only
             * @member
             * @type {number}
             */
            this["CommitInterval"] = 0;
        }
        if (!("Branch" in $$source)) {
            /**
             * branch to sync, empty = use current branch
             * @member
             * @type {string}
             */
            this["Branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitSyncConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitSyncConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitSyncConfig(/** @type {Partial<GitSyncConfig>} */($$parsedSource));
    }
}

export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("QuickCaptureEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["QuickCaptureEnabled"] = false;
        }
        if (!("QuickCaptureModifiers" in $$source)) {
            /**
             * e.g., ["Ctrl", "Shift"]
             * @member
             * @type {string[]}
             */
            this["QuickCaptureModifiers"] = [];
        }
        if (!("QuickCaptureKey" in $$source)) {
            /**
             * e.g., "N"
             * @member
             * @type {string}
             */
            this["QuickCaptureKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("QuickCaptureModifiers" in $$parsedSource) {
            $$parsedSource["QuickCaptureModifiers"] = $$createField1_0($$parsedSource["QuickCaptureModifiers"]);
        }
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
