// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GitSyncConfig {
    "Enabled": boolean;
    "AutoCommit": boolean;
    "AutoPush": boolean;

    /**
     * minutes between auto-commits, 0 = manual only
     */
    "CommitInterval": number;

    /** Creates a new GitSyncConfig instance. */
    constructor($$source: Partial<GitSyncConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("AutoCommit" in $$source)) {
            this["AutoCommit"] = false;
        }
        if (!("AutoPush" in $$source)) {
            this["AutoPush"] = false;
        }
        if (!("CommitInterval" in $$source)) {
            this["CommitInterval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitSyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GitSyncConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitSyncConfig($$parsedSource as Partial<GitSyncConfig>);
    }
}
