// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackupConfig {
    "Enabled": boolean;

    /**
     * number of backups to retain, 0 = unlimited
     */
    "MaxBackups": number;

    /** Creates a new BackupConfig instance. */
    constructor($$source: Partial<BackupConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("MaxBackups" in $$source)) {
            this["MaxBackups"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupConfig($$parsedSource as Partial<BackupConfig>);
    }
}

export class GitSyncConfig {
    "Enabled": boolean;
    "AutoCommit": boolean;
    "AutoPush": boolean;

    /**
     * minutes between auto-commits, 0 = manual only
     */
    "CommitInterval": number;

    /**
     * branch to sync, empty = use current branch
     */
    "Branch": string;

    /** Creates a new GitSyncConfig instance. */
    constructor($$source: Partial<GitSyncConfig> = {}) {
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("AutoCommit" in $$source)) {
            this["AutoCommit"] = false;
        }
        if (!("AutoPush" in $$source)) {
            this["AutoPush"] = false;
        }
        if (!("CommitInterval" in $$source)) {
            this["CommitInterval"] = 0;
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitSyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GitSyncConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitSyncConfig($$parsedSource as Partial<GitSyncConfig>);
    }
}

export class HotkeyConfig {
    "QuickCaptureEnabled": boolean;

    /**
     * e.g., ["Ctrl", "Shift"]
     */
    "QuickCaptureModifiers": string[];

    /**
     * e.g., "N"
     */
    "QuickCaptureKey": string;

    /** Creates a new HotkeyConfig instance. */
    constructor($$source: Partial<HotkeyConfig> = {}) {
        if (!("QuickCaptureEnabled" in $$source)) {
            this["QuickCaptureEnabled"] = false;
        }
        if (!("QuickCaptureModifiers" in $$source)) {
            this["QuickCaptureModifiers"] = [];
        }
        if (!("QuickCaptureKey" in $$source)) {
            this["QuickCaptureKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HotkeyConfig {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("QuickCaptureModifiers" in $$parsedSource) {
            $$parsedSource["QuickCaptureModifiers"] = $$createField1_0($$parsedSource["QuickCaptureModifiers"]);
        }
        return new HotkeyConfig($$parsedSource as Partial<HotkeyConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
