// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GitSyncConfig {
    /**
     * Creates a new GitSyncConfig instance.
     * @param {Partial<GitSyncConfig>} [$$source = {}] - The source object to create the GitSyncConfig.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("AutoCommit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoCommit"] = false;
        }
        if (!("AutoPush" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoPush"] = false;
        }
        if (!("CommitInterval" in $$source)) {
            /**
             * minutes between auto-commits, 0 = manual only
             * @member
             * @type {number}
             */
            this["CommitInterval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitSyncConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitSyncConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitSyncConfig(/** @type {Partial<GitSyncConfig>} */($$parsedSource));
    }
}
