// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "defaultWidth": number;
    "defaultHeight": number;
    "minWidth": number;
    "minHeight": number;
    "maxWidth": number;
    "maxHeight": number;
    "windowMode": string;
    "isFrameless": boolean;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("defaultWidth" in $$source)) {
            this["defaultWidth"] = 0;
        }
        if (!("defaultHeight" in $$source)) {
            this["defaultHeight"] = 0;
        }
        if (!("minWidth" in $$source)) {
            this["minWidth"] = 0;
        }
        if (!("minHeight" in $$source)) {
            this["minHeight"] = 0;
        }
        if (!("maxWidth" in $$source)) {
            this["maxWidth"] = 0;
        }
        if (!("maxHeight" in $$source)) {
            this["maxHeight"] = 0;
        }
        if (!("windowMode" in $$source)) {
            this["windowMode"] = "";
        }
        if (!("isFrameless" in $$source)) {
            this["isFrameless"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
