// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("defaultWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["defaultWidth"] = 0;
        }
        if (!("defaultHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["defaultHeight"] = 0;
        }
        if (!("minWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minWidth"] = 0;
        }
        if (!("minHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minHeight"] = 0;
        }
        if (!("maxWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxWidth"] = 0;
        }
        if (!("maxHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxHeight"] = 0;
        }
        if (!("windowMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["windowMode"] = "";
        }
        if (!("isFrameless" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFrameless"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}
