// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(3982745460).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWindowMode() {
    return $Call.ByID(2604052157);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFrameless() {
    return $Call.ByID(1731078438);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowMode(mode) {
    return $Call.ByID(3062783441, mode);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
