// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(3982745460).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetWindowMode(): $CancellablePromise<string> {
    return $Call.ByID(2604052157);
}

export function IsFrameless(): $CancellablePromise<boolean> {
    return $Call.ByID(1731078438);
}

export function SetWindowMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3062783441, mode);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
