// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    "version": string;
    "buildCommit": string;
    "buildDate": string;
    "platform": string;
    "goVersion": string;
    "databasePath": string;
    "logLevel": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("buildCommit" in $$source)) {
            this["buildCommit"] = "";
        }
        if (!("buildDate" in $$source)) {
            this["buildDate"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("goVersion" in $$source)) {
            this["goVersion"] = "";
        }
        if (!("databasePath" in $$source)) {
            this["databasePath"] = "";
        }
        if (!("logLevel" in $$source)) {
            this["logLevel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

export class DatabaseInfo {
    "entriesCount": number;
    "projectsCount": number;
    "tagsCount": number;
    "storageUsed": string;

    /** Creates a new DatabaseInfo instance. */
    constructor($$source: Partial<DatabaseInfo> = {}) {
        if (!("entriesCount" in $$source)) {
            this["entriesCount"] = 0;
        }
        if (!("projectsCount" in $$source)) {
            this["projectsCount"] = 0;
        }
        if (!("tagsCount" in $$source)) {
            this["tagsCount"] = 0;
        }
        if (!("storageUsed" in $$source)) {
            this["storageUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo($$parsedSource as Partial<DatabaseInfo>);
    }
}

export class SystemInfo {
    "app": AppInfo;
    "database": DatabaseInfo;

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("app" in $$source)) {
            this["app"] = (new AppInfo());
        }
        if (!("database" in $$source)) {
            this["database"] = (new DatabaseInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("database" in $$parsedSource) {
            $$parsedSource["database"] = $$createField1_0($$parsedSource["database"]);
        }
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

// Private type creation functions
const $$createType0 = AppInfo.createFrom;
const $$createType1 = DatabaseInfo.createFrom;
