// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("buildCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildCommit"] = "";
        }
        if (!("buildDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildDate"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("logLevel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logLevel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

export class DatabaseInfo {
    /**
     * Creates a new DatabaseInfo instance.
     * @param {Partial<DatabaseInfo>} [$$source = {}] - The source object to create the DatabaseInfo.
     */
    constructor($$source = {}) {
        if (!("entriesCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entriesCount"] = 0;
        }
        if (!("projectsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectsCount"] = 0;
        }
        if (!("tagsCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tagsCount"] = 0;
        }
        if (!("storageUsed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storageUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo(/** @type {Partial<DatabaseInfo>} */($$parsedSource));
    }
}

export class SystemInfo {
    /**
     * Creates a new SystemInfo instance.
     * @param {Partial<SystemInfo>} [$$source = {}] - The source object to create the SystemInfo.
     */
    constructor($$source = {}) {
        if (!("app" in $$source)) {
            /**
             * @member
             * @type {AppInfo}
             */
            this["app"] = (new AppInfo());
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {DatabaseInfo}
             */
            this["database"] = (new DatabaseInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("database" in $$parsedSource) {
            $$parsedSource["database"] = $$createField1_0($$parsedSource["database"]);
        }
        return new SystemInfo(/** @type {Partial<SystemInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AppInfo.createFrom;
const $$createType1 = DatabaseInfo.createFrom;
