// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BackgroundQuit(): $CancellablePromise<void> {
    return $Call.ByID(1341224654);
}

export function CheckGitInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(3009163209);
}

export function ForceQuit(): $CancellablePromise<void> {
    return $Call.ByID(2214529267);
}

export function GetAppScale(): $CancellablePromise<number> {
    return $Call.ByID(731302552);
}

export function GetCurrentDataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1375740355);
}

export function GetGitStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(1825114647).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGitSyncConfig(): $CancellablePromise<config$0.GitSyncConfig> {
    return $Call.ByID(1575361836).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetKeepInBackground(): $CancellablePromise<boolean> {
    return $Call.ByID(3067148649);
}

export function GetStartHidden(): $CancellablePromise<boolean> {
    return $Call.ByID(2907183281);
}

export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(3308718230).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GitPull(): $CancellablePromise<void> {
    return $Call.ByID(2119526436);
}

export function GitPush(): $CancellablePromise<void> {
    return $Call.ByID(2225164767);
}

export function LogFromFrontend(level: string, message: string, data: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(407285753, level, message, data);
}

export function MigrateToGitDirectory(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(4210655868, targetPath);
}

export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(103548900);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2095272102);
}

export function ReindexDatabase(): $CancellablePromise<void> {
    return $Call.ByID(1772458609);
}

export function SetAppScale(scale: number): $CancellablePromise<void> {
    return $Call.ByID(4133372804, scale);
}

export function SetDBPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(816597254, path);
}

export function SetGitSyncConfig(cfg: config$0.GitSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(3328767048, cfg);
}

export function SetIndexer(idx: indexer$0.Indexer | null): $CancellablePromise<void> {
    return $Call.ByID(671503490, idx);
}

export function SetKeepInBackground(keep: boolean): $CancellablePromise<void> {
    return $Call.ByID(500746405, keep);
}

export function SetLogLevel(level: string): $CancellablePromise<void> {
    return $Call.ByID(4186758403, level);
}

export function SetShutdownHandler(handler: any): $CancellablePromise<void> {
    return $Call.ByID(2494822927, handler);
}

export function SetStartHidden(hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(283794453, hidden);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(138335344);
}

export function SyncNow(): $CancellablePromise<git$0.SyncResult | null> {
    return $Call.ByID(4024210634).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ValidateMigrationTarget(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(1267261344, targetPath);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = config$0.GitSyncConfig.createFrom;
const $$createType2 = $models.SystemInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = git$0.SyncResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
