// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as migration$0 from "../migration/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function BackgroundQuit() {
    return $Call.ByID(1341224654);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckGitInstalled() {
    return $Call.ByID(3009163209);
}

/**
 * CheckMigrationConflicts detects if both local and target have vault data,
 * and returns statistics for both vaults.
 * @param {string} targetPath
 * @returns {$CancellablePromise<migration$0.MigrationConflictInfo | null>}
 */
export function CheckMigrationConflicts(targetPath) {
    return $Call.ByID(1424366808, targetPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ForceQuit() {
    return $Call.ByID(2214529267);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetAppScale() {
    return $Call.ByID(731302552);
}

/**
 * GetAvailableHotkeyKeys returns the list of supported keys for hotkey configuration.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableHotkeyKeys() {
    return $Call.ByID(3439795820).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAvailableHotkeyModifiers returns the list of supported modifiers for hotkey configuration.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableHotkeyModifiers() {
    return $Call.ByID(3059828422).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentDataDirectory() {
    return $Call.ByID(1375740355);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentGitBranch() {
    return $Call.ByID(4202279096);
}

/**
 * GetDataDirectoryEnvVar returns the YANTA_DATA_DIR value if set, empty string otherwise.
 * @returns {$CancellablePromise<string>}
 */
export function GetDataDirectoryEnvVar() {
    return $Call.ByID(2317422642);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetGitBranches() {
    return $Call.ByID(2912890353).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetGitStatus() {
    return $Call.ByID(1825114647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.GitSyncConfig>}
 */
export function GetGitSyncConfig() {
    return $Call.ByID(1575361836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHotkeyConfig returns the current hotkey configuration.
 * @returns {$CancellablePromise<config$0.HotkeyConfig>}
 */
export function GetHotkeyConfig() {
    return $Call.ByID(1788811887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetKeepInBackground() {
    return $Call.ByID(3067148649);
}

/**
 * GetPlatform returns the current platform name.
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatform() {
    return $Call.ByID(3548419224);
}

/**
 * GetShowFooterHints returns the current footer hints visibility setting.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetShowFooterHints() {
    return $Call.ByID(57552729);
}

/**
 * GetShowShortcutTooltips returns the current shortcut tooltips visibility setting.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetShowShortcutTooltips() {
    return $Call.ByID(1811891940);
}

/**
 * GetSidebarVisible returns the current sidebar visibility setting.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSidebarVisible() {
    return $Call.ByID(2793125877);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartHidden() {
    return $Call.ByID(2907183281);
}

/**
 * @returns {$CancellablePromise<$models.SystemInfo | null>}
 */
export function GetSystemInfo() {
    return $Call.ByID(3308718230).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GitPull() {
    return $Call.ByID(2119526436);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GitPush() {
    return $Call.ByID(2225164767);
}

/**
 * IsCommandLineEnabled returns whether the command line feature is enabled.
 * Controlled by YANTA_ENABLE_COMMAND_LINE environment variable.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsCommandLineEnabled() {
    return $Call.ByID(3125444353);
}

/**
 * IsDataDirectoryOverridden returns true if YANTA_DATA_DIR environment variable is set,
 * which means any changes to the data directory via the UI won't take effect until
 * the env var is unset.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDataDirectoryOverridden() {
    return $Call.ByID(1956272108);
}

/**
 * @param {string} level
 * @param {string} message
 * @param {{ [_: string]: any }} data
 * @returns {$CancellablePromise<void>}
 */
export function LogFromFrontend(level, message, data) {
    return $Call.ByID(407285753, level, message, data);
}

/**
 * @param {string} targetPath
 * @param {migration$0.MigrationStrategy} strategy
 * @returns {$CancellablePromise<void>}
 */
export function MigrateToGitDirectory(targetPath, strategy) {
    return $Call.ByID(4210655868, targetPath, strategy);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(103548900);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(2095272102);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReindexDatabase() {
    return $Call.ByID(1772458609);
}

/**
 * @param {number} scale
 * @returns {$CancellablePromise<void>}
 */
export function SetAppScale(scale) {
    return $Call.ByID(4133372804, scale);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetDBPath(path) {
    return $Call.ByID(816597254, path);
}

/**
 * @param {config$0.GitSyncConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetGitSyncConfig(cfg) {
    return $Call.ByID(3328767048, cfg);
}

/**
 * SetHotkeyConfig updates the hotkey configuration and triggers live reconfiguration.
 * @param {config$0.HotkeyConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkeyConfig(cfg) {
    return $Call.ByID(10862067, cfg);
}

/**
 * @param {any} handler
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkeyReconfigureHandler(handler) {
    return $Call.ByID(888177452, handler);
}

/**
 * @param {indexer$0.Indexer | null} idx
 * @returns {$CancellablePromise<void>}
 */
export function SetIndexer(idx) {
    return $Call.ByID(671503490, idx);
}

/**
 * @param {boolean} keep
 * @returns {$CancellablePromise<void>}
 */
export function SetKeepInBackground(keep) {
    return $Call.ByID(500746405, keep);
}

/**
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(4186758403, level);
}

/**
 * SetShowFooterHints updates the footer hints visibility setting.
 * @param {boolean} show
 * @returns {$CancellablePromise<void>}
 */
export function SetShowFooterHints(show) {
    return $Call.ByID(660001957, show);
}

/**
 * SetShowShortcutTooltips updates the shortcut tooltips visibility setting.
 * @param {boolean} show
 * @returns {$CancellablePromise<void>}
 */
export function SetShowShortcutTooltips(show) {
    return $Call.ByID(2030692744, show);
}

/**
 * @param {any} handler
 * @returns {$CancellablePromise<void>}
 */
export function SetShutdownHandler(handler) {
    return $Call.ByID(2494822927, handler);
}

/**
 * SetSidebarVisible updates the sidebar visibility setting.
 * @param {boolean} visible
 * @returns {$CancellablePromise<void>}
 */
export function SetSidebarVisible(visible) {
    return $Call.ByID(4066415849, visible);
}

/**
 * @param {boolean} hidden
 * @returns {$CancellablePromise<void>}
 */
export function SetStartHidden(hidden) {
    return $Call.ByID(283794453, hidden);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(138335344);
}

/**
 * @returns {$CancellablePromise<git$0.SyncResult | null>}
 */
export function SyncNow() {
    return $Call.ByID(4024210634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} targetPath
 * @returns {$CancellablePromise<void>}
 */
export function ValidateMigrationTarget(targetPath) {
    return $Call.ByID(1267261344, targetPath);
}

// Private type creation functions
const $$createType0 = migration$0.MigrationConflictInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = config$0.GitSyncConfig.createFrom;
const $$createType5 = config$0.HotkeyConfig.createFrom;
const $$createType6 = $models.SystemInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = git$0.SyncResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
