// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function BackgroundQuit() {
    return $Call.ByID(1341224654);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckGitInstalled() {
    return $Call.ByID(3009163209);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ForceQuit() {
    return $Call.ByID(2214529267);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetAppScale() {
    return $Call.ByID(731302552);
}

/**
 * GetAvailableHotkeyKeys returns the list of supported keys for hotkey configuration.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableHotkeyKeys() {
    return $Call.ByID(3439795820).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAvailableHotkeyModifiers returns the list of supported modifiers for hotkey configuration.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableHotkeyModifiers() {
    return $Call.ByID(3059828422).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentDataDirectory() {
    return $Call.ByID(1375740355);
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetGitStatus() {
    return $Call.ByID(1825114647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.GitSyncConfig>}
 */
export function GetGitSyncConfig() {
    return $Call.ByID(1575361836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetHotkeyConfig returns the current hotkey configuration.
 * @returns {$CancellablePromise<config$0.HotkeyConfig>}
 */
export function GetHotkeyConfig() {
    return $Call.ByID(1788811887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetKeepInBackground() {
    return $Call.ByID(3067148649);
}

/**
 * GetPlatform returns the current platform name.
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatform() {
    return $Call.ByID(3548419224);
}

/**
 * GetShowFooterHints returns the current footer hints visibility setting.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetShowFooterHints() {
    return $Call.ByID(57552729);
}

/**
 * GetSidebarVisible returns the current sidebar visibility setting.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSidebarVisible() {
    return $Call.ByID(2793125877);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartHidden() {
    return $Call.ByID(2907183281);
}

/**
 * @returns {$CancellablePromise<$models.SystemInfo | null>}
 */
export function GetSystemInfo() {
    return $Call.ByID(3308718230).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GitPull() {
    return $Call.ByID(2119526436);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GitPush() {
    return $Call.ByID(2225164767);
}

/**
 * @param {string} level
 * @param {string} message
 * @param {{ [_: string]: any }} data
 * @returns {$CancellablePromise<void>}
 */
export function LogFromFrontend(level, message, data) {
    return $Call.ByID(407285753, level, message, data);
}

/**
 * @param {string} targetPath
 * @returns {$CancellablePromise<void>}
 */
export function MigrateToGitDirectory(targetPath) {
    return $Call.ByID(4210655868, targetPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(103548900);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(2095272102);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ReindexDatabase() {
    return $Call.ByID(1772458609);
}

/**
 * @param {number} scale
 * @returns {$CancellablePromise<void>}
 */
export function SetAppScale(scale) {
    return $Call.ByID(4133372804, scale);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetDBPath(path) {
    return $Call.ByID(816597254, path);
}

/**
 * @param {config$0.GitSyncConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetGitSyncConfig(cfg) {
    return $Call.ByID(3328767048, cfg);
}

/**
 * SetHotkeyConfig updates the hotkey configuration and triggers live reconfiguration.
 * @param {config$0.HotkeyConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkeyConfig(cfg) {
    return $Call.ByID(10862067, cfg);
}

/**
 * @param {any} handler
 * @returns {$CancellablePromise<void>}
 */
export function SetHotkeyReconfigureHandler(handler) {
    return $Call.ByID(888177452, handler);
}

/**
 * @param {indexer$0.Indexer | null} idx
 * @returns {$CancellablePromise<void>}
 */
export function SetIndexer(idx) {
    return $Call.ByID(671503490, idx);
}

/**
 * @param {boolean} keep
 * @returns {$CancellablePromise<void>}
 */
export function SetKeepInBackground(keep) {
    return $Call.ByID(500746405, keep);
}

/**
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(4186758403, level);
}

/**
 * SetShowFooterHints updates the footer hints visibility setting.
 * @param {boolean} show
 * @returns {$CancellablePromise<void>}
 */
export function SetShowFooterHints(show) {
    return $Call.ByID(660001957, show);
}

/**
 * @param {any} handler
 * @returns {$CancellablePromise<void>}
 */
export function SetShutdownHandler(handler) {
    return $Call.ByID(2494822927, handler);
}

/**
 * SetSidebarVisible updates the sidebar visibility setting.
 * @param {boolean} visible
 * @returns {$CancellablePromise<void>}
 */
export function SetSidebarVisible(visible) {
    return $Call.ByID(4066415849, visible);
}

/**
 * @param {boolean} hidden
 * @returns {$CancellablePromise<void>}
 */
export function SetStartHidden(hidden) {
    return $Call.ByID(283794453, hidden);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(138335344);
}

/**
 * @returns {$CancellablePromise<git$0.SyncResult | null>}
 */
export function SyncNow() {
    return $Call.ByID(4024210634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} targetPath
 * @returns {$CancellablePromise<void>}
 */
export function ValidateMigrationTarget(targetPath) {
    return $Call.ByID(1267261344, targetPath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = config$0.GitSyncConfig.createFrom;
const $$createType3 = config$0.HotkeyConfig.createFrom;
const $$createType4 = $models.SystemInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = git$0.SyncResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
