// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "../git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as migration$0 from "../migration/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BackgroundQuit(): $CancellablePromise<void> {
    return $Call.ByID(1341224654);
}

export function CheckGitInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(3009163209);
}

/**
 * CheckMigrationConflicts detects if both local and target have vault data,
 * and returns statistics for both vaults.
 */
export function CheckMigrationConflicts(targetPath: string): $CancellablePromise<migration$0.MigrationConflictInfo | null> {
    return $Call.ByID(1424366808, targetPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ForceQuit(): $CancellablePromise<void> {
    return $Call.ByID(2214529267);
}

export function GetAppScale(): $CancellablePromise<number> {
    return $Call.ByID(731302552);
}

/**
 * GetAvailableHotkeyKeys returns the list of supported keys for hotkey configuration.
 */
export function GetAvailableHotkeyKeys(): $CancellablePromise<string[]> {
    return $Call.ByID(3439795820).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAvailableHotkeyModifiers returns the list of supported modifiers for hotkey configuration.
 */
export function GetAvailableHotkeyModifiers(): $CancellablePromise<string[]> {
    return $Call.ByID(3059828422).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetCurrentDataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1375740355);
}

export function GetCurrentGitBranch(): $CancellablePromise<string> {
    return $Call.ByID(4202279096);
}

/**
 * GetDataDirectoryEnvVar returns the YANTA_DATA_DIR value if set, empty string otherwise.
 */
export function GetDataDirectoryEnvVar(): $CancellablePromise<string> {
    return $Call.ByID(2317422642);
}

export function GetGitBranches(): $CancellablePromise<string[]> {
    return $Call.ByID(2912890353).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGitStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(1825114647).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetGitSyncConfig(): $CancellablePromise<config$0.GitSyncConfig> {
    return $Call.ByID(1575361836).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetHotkeyConfig returns the current hotkey configuration.
 */
export function GetHotkeyConfig(): $CancellablePromise<config$0.HotkeyConfig> {
    return $Call.ByID(1788811887).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetKeepInBackground(): $CancellablePromise<boolean> {
    return $Call.ByID(3067148649);
}

/**
 * GetPlatform returns the current platform name.
 */
export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByID(3548419224);
}

/**
 * GetShowFooterHints returns the current footer hints visibility setting.
 */
export function GetShowFooterHints(): $CancellablePromise<boolean> {
    return $Call.ByID(57552729);
}

/**
 * GetShowShortcutTooltips returns the current shortcut tooltips visibility setting.
 */
export function GetShowShortcutTooltips(): $CancellablePromise<boolean> {
    return $Call.ByID(1811891940);
}

/**
 * GetSidebarVisible returns the current sidebar visibility setting.
 */
export function GetSidebarVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(2793125877);
}

export function GetStartHidden(): $CancellablePromise<boolean> {
    return $Call.ByID(2907183281);
}

export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(3308718230).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GitPull(): $CancellablePromise<void> {
    return $Call.ByID(2119526436);
}

export function GitPush(): $CancellablePromise<void> {
    return $Call.ByID(2225164767);
}

/**
 * IsCommandLineEnabled returns whether the command line feature is enabled.
 * Controlled by YANTA_ENABLE_COMMAND_LINE environment variable.
 */
export function IsCommandLineEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3125444353);
}

/**
 * IsDataDirectoryOverridden returns true if YANTA_DATA_DIR environment variable is set,
 * which means any changes to the data directory via the UI won't take effect until
 * the env var is unset.
 */
export function IsDataDirectoryOverridden(): $CancellablePromise<boolean> {
    return $Call.ByID(1956272108);
}

export function LogFromFrontend(level: string, message: string, data: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(407285753, level, message, data);
}

export function MigrateToGitDirectory(targetPath: string, strategy: migration$0.MigrationStrategy): $CancellablePromise<void> {
    return $Call.ByID(4210655868, targetPath, strategy);
}

export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(103548900);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2095272102);
}

export function ReindexDatabase(): $CancellablePromise<void> {
    return $Call.ByID(1772458609);
}

export function SetAppScale(scale: number): $CancellablePromise<void> {
    return $Call.ByID(4133372804, scale);
}

export function SetDBPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(816597254, path);
}

export function SetGitSyncConfig(cfg: config$0.GitSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(3328767048, cfg);
}

/**
 * SetHotkeyConfig updates the hotkey configuration and triggers live reconfiguration.
 */
export function SetHotkeyConfig(cfg: config$0.HotkeyConfig): $CancellablePromise<void> {
    return $Call.ByID(10862067, cfg);
}

export function SetHotkeyReconfigureHandler(handler: any): $CancellablePromise<void> {
    return $Call.ByID(888177452, handler);
}

export function SetIndexer(idx: indexer$0.Indexer | null): $CancellablePromise<void> {
    return $Call.ByID(671503490, idx);
}

export function SetKeepInBackground(keep: boolean): $CancellablePromise<void> {
    return $Call.ByID(500746405, keep);
}

export function SetLogLevel(level: string): $CancellablePromise<void> {
    return $Call.ByID(4186758403, level);
}

/**
 * SetShowFooterHints updates the footer hints visibility setting.
 */
export function SetShowFooterHints(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(660001957, show);
}

/**
 * SetShowShortcutTooltips updates the shortcut tooltips visibility setting.
 */
export function SetShowShortcutTooltips(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(2030692744, show);
}

export function SetShutdownHandler(handler: any): $CancellablePromise<void> {
    return $Call.ByID(2494822927, handler);
}

/**
 * SetSidebarVisible updates the sidebar visibility setting.
 */
export function SetSidebarVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(4066415849, visible);
}

export function SetStartHidden(hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(283794453, hidden);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(138335344);
}

export function SyncNow(): $CancellablePromise<git$0.SyncResult | null> {
    return $Call.ByID(4024210634).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ValidateMigrationTarget(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(1267261344, targetPath);
}

// Private type creation functions
const $$createType0 = migration$0.MigrationConflictInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = config$0.GitSyncConfig.createFrom;
const $$createType5 = config$0.HotkeyConfig.createFrom;
const $$createType6 = $models.SystemInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = git$0.SyncResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
