// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Parse(arg1) {
  return window['go']['commandline']['DocumentCommands']['Parse'](arg1);
}

export function ParseWithContext(arg1, arg2) {
  return window['go']['commandline']['DocumentCommands']['ParseWithContext'](arg1, arg2);
}

export function ParseWithDocument(arg1, arg2) {
  return window['go']['commandline']['DocumentCommands']['ParseWithDocument'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['commandline']['DocumentCommands']['SetContext'](arg1);
}

export function SetCurrentDocument(arg1) {
  return window['go']['commandline']['DocumentCommands']['SetCurrentDocument'](arg1);
}
