// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commandline} from '../models';
import {context} from '../models';

export function Parse(arg1:string):Promise<commandline.DocumentResult>;

export function ParseWithContext(arg1:string,arg2:string):Promise<commandline.DocumentResult>;

export function ParseWithDocument(arg1:string,arg2:string):Promise<commandline.DocumentResult>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetCurrentDocument(arg1:string):Promise<void>;
