// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {commandline} from '../models';
import {context} from '../models';

export function GetProjectCache():Promise<project.Cache>;

export function Parse(arg1:string):Promise<commandline.GlobalResult>;

export function SetContext(arg1:context.Context):Promise<void>;
