// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjectCache() {
  return window['go']['commandline']['GlobalCommands']['GetProjectCache']();
}

export function Parse(arg1) {
  return window['go']['commandline']['GlobalCommands']['Parse'](arg1);
}

export function SetContext(arg1) {
  return window['go']['commandline']['GlobalCommands']['SetContext'](arg1);
}
