// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "document" or "note"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("projectAlias" in $$source)) {
            /**
             * filled for both
             * @member
             * @type {string}
             */
            this["projectAlias"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * only for notes (entry ID within journal file)
             * @member
             * @type {string | undefined}
             */
            this["noteId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}
