// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Result {
    "id": string;
    "title": string;
    "snippet": string;
    "updated": string;

    /**
     * "document" or "note"
     */
    "type": string;

    /**
     * filled for both
     */
    "projectAlias": string;

    /**
     * only for notes (entry ID within journal file)
     */
    "noteId"?: string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("projectAlias" in $$source)) {
            this["projectAlias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
